INSERT INTO country (country_iso, name) VALUES ('ASM', 'American Samoa');
INSERT INTO country (country_iso, name) VALUES ('AIA', 'Anguilla');
INSERT INTO country (country_iso, name) VALUES ('ABW', 'Aruba');
INSERT INTO country (country_iso, name) VALUES ('BMU', 'Bermuda');
INSERT INTO country (country_iso, name) VALUES ('BES', 'Bonaire, Sint Eustatius and Saba');
INSERT INTO country (country_iso, name) VALUES ('VGB', 'British Virgin Islands');
INSERT INTO country (country_iso, name) VALUES ('CYM', 'Cayman Islands');
INSERT INTO country (country_iso, name) VALUES ('CUW', 'Curaçao');
INSERT INTO country (country_iso, name) VALUES ('FLK', 'Falkland Islands (Malvinas)');
INSERT INTO country (country_iso, name) VALUES ('GUF', 'French Guiana');
INSERT INTO country (country_iso, name) VALUES ('PYF', 'French Polynesia');
INSERT INTO country (country_iso, name) VALUES ('GIB', 'Gibraltar');
INSERT INTO country (country_iso, name) VALUES ('GRL', 'Greenland');
INSERT INTO country (country_iso, name) VALUES ('GLP', 'Guadeloupe');
INSERT INTO country (country_iso, name) VALUES ('GUM', 'Guam');
INSERT INTO country (country_iso, name) VALUES ('GGY', 'Guernsey');
INSERT INTO country (country_iso, name) VALUES ('VAT', 'Holy See');
INSERT INTO country (country_iso, name) VALUES ('IMN', 'Isle of Man');
INSERT INTO country (country_iso, name) VALUES ('JEY', 'Jersey');
INSERT INTO country (country_iso, name) VALUES ('LIE', 'Liechtenstein');
INSERT INTO country (country_iso, name) VALUES ('MTQ', 'Martinique');
INSERT INTO country (country_iso, name) VALUES ('MYT', 'Mayotte');
INSERT INTO country (country_iso, name) VALUES ('MSR', 'Montserrat');
INSERT INTO country (country_iso, name) VALUES ('NCL', 'New Caledonia');
INSERT INTO country (country_iso, name) VALUES ('NFK', 'Norfolk Island');
INSERT INTO country (country_iso, name) VALUES ('MNP', 'Northern Mariana Islands');
INSERT INTO country (country_iso, name) VALUES ('PSE', 'Occupied Palestinian Territory');
INSERT INTO country (country_iso, name) VALUES ('PCN', 'Pitcairn Islands');
INSERT INTO country (country_iso, name) VALUES ('PRI', 'Puerto Rico');
INSERT INTO country (country_iso, name) VALUES ('REU', 'Réunion');
INSERT INTO country (country_iso, name) VALUES ('MAF', 'Saint Martin (French part)');
INSERT INTO country (country_iso, name) VALUES ('SPM', 'Saint Pierre and Miquelon');
INSERT INTO country (country_iso, name) VALUES ('BLM', 'Saint-Barthélemy');
INSERT INTO country (country_iso, name) VALUES ('SXM', 'Sint Maarten (Dutch part)');
INSERT INTO country (country_iso, name) VALUES ('SJM', 'Svalbard and Jan Mayen Islands');
INSERT INTO country (country_iso, name) VALUES ('TCA', 'Turks and Caicos Islands');
INSERT INTO country (country_iso, name) VALUES ('VIR', 'United States Virgin Islands');
INSERT INTO country (country_iso, name) VALUES ('WLF', 'Wallis and Futuna Islands');
INSERT INTO country (country_iso, name) VALUES ('ESH', 'Western Sahara');
