TRUNCATE TABLE fra_user CASCADE;

INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (36, 'jonascedergren58@gmail.com', 'EH', 'jonascedergren58@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (38, 'globalforestsurvey@gmail.com', 'Monica NC', 'globalforestsurvey@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (35, 'perttu.auramo@gmail.com', 'Test User', 'perttu.auramo@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (19, 'rw.michalak@gmail.com', 'Roman', 'rw.michalak@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (5, 'perttu.auramo@reaktor.com', 'Perttu Auramo', 'auramo@reaktor.fi', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (9, 'toni.strandell@reaktor.com', 'Toni Strandell', 'strandel@reaktor.fi', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (10, 'nwaltham.fao@gmail.com', 'Nicholas Waltham', 'nwaltham.fao@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (11, 'sara.maulo@gmail.com', 'Sara Maulo', 'sara.maulo@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (39, 'fraplataform@gmail.com', 'Ojje Rev', 'fraplataform@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (4, 'Cosimo.togna@fao.org', 'Cosimo Togna', 'mino.togna@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (13, 'fraplatform@gmail.com', 'Reviewer Örjan', 'orjan.fao@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (12, 'Alexandra.Zmachynskaya@fao.org', 'Alexandra Zmachynskaya', 'alex.zmachynskaya@gmail.com', 'ru');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (8, 'Anssi.Pekkarinen@fao.org', 'Anssi Pekkarinen', 'anssioffice@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (30, 'sean.p.healey01@gmail.com', 'Sean Healey', 'sean.p.healey01@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (31, 'jobertovf@gmail.com', 'Joberto Freitas', 'jobertovf@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (14, 'platformfra@gmail.com', 'NC Monica', 'monica.garzuglia@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (7, 'mathias.lindholm@gmail.com', 'Conway', 'conway@reaktor.fi', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (33, 'crisvtellez@gmail.com', 'María Torres-Quevedo', 'crisvtellez@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (27, 'pina.cortez.work@gmail.com', 'Leticia', 'pina.cortez.work@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (6, 'joni.rajanen@reaktor.com', 'Joni Rajanen', 'jonira@reaktor.fi', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (15, 'soulsu@gmail.com', 'Susy Domenicano', 'soulsu@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (16, 'srjbridge@gmail.com', 'Simon Bridge', 'srjbridge@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (17, 'ivana.marincelj@gmail.com', 'Ivana Pešut', 'ivana.marincelj@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (18, 'rastislav.rasi@foresteurope.org', 'Rastislav Raši', 'rastislav.rasi@foresteurope.org', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (40, 'remi.dannunzio@gmail.com', 'Remi', 'remi.dannunzio@gmail.com', 'fr');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (20, 'stemtomt@gmail.com', 'Stein Tomter', 'stemtomt@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (21, 'grahamhstinson@gmail.com', 'Graham Stinson', 'grahamhstinson@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (22, 'soswaltfs@gmail.com', 'Sonja Oswalt', 'soswaltfs@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (23, 'thomas.brandeis@gmail.com', 'Thomas Brandeis', 'thomas.brandeis@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (25, 'larsgunnar.marklund@gmail.com', 'Lars Gunnar Marklund', 'larsgunnar.marklund@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (34, 'hebbetaxen@gmail.com', 'Svante Claesson', 'hebbetaxen@gmail.com', 'en');
INSERT INTO fra_user (id, email, name, login_email, lang) VALUES (37, 'mathias.lindholm@gmail.com', 'Mathias', 'mathias.lindholm@gmail.com', 'en');

INSERT INTO user_country_role (user_id, country_iso, role) VALUES (13, null, 'ADMINISTRATOR');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (4, null, 'ADMINISTRATOR');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (36, 'SSD', 'NATIONAL_CORRESPONDENT');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (14, 'PLW', 'NATIONAL_CORRESPONDENT');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (5, null, 'ADMINISTRATOR');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (6, null, 'ADMINISTRATOR');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (7, null, 'ADMINISTRATOR');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (8, null, 'ADMINISTRATOR');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (15, 'CAN', 'NATIONAL_CORRESPONDENT');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (16, 'CAN', 'NATIONAL_CORRESPONDENT');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (17, 'HRV', 'NATIONAL_CORRESPONDENT');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (18, 'SVK', 'NATIONAL_CORRESPONDENT');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (19, 'SWZ', 'NATIONAL_CORRESPONDENT');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (20, 'NOR', 'REVIEWER');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (21, 'CAN', 'NATIONAL_CORRESPONDENT');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (22, 'USA', 'NATIONAL_CORRESPONDENT');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (23, 'USA', 'NATIONAL_CORRESPONDENT');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (9, null, 'ADMINISTRATOR');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (10, null, 'ADMINISTRATOR');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (30, 'USA', 'NATIONAL_CORRESPONDENT');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (31, 'BRA', 'NATIONAL_CORRESPONDENT');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (33, 'ESP', 'NATIONAL_CORRESPONDENT');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (34, 'SWE', 'REVIEWER');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (8, 'X01', 'REVIEWER');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (14, 'X01', 'REVIEWER');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (11, null, 'ADMINISTRATOR');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (12, null, 'ADMINISTRATOR');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (14, null, 'ADMINISTRATOR');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (25, null, 'ADMINISTRATOR');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (35, 'AFG', 'NATIONAL_CORRESPONDENT');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (19, 'POL', 'NATIONAL_CORRESPONDENT');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (27, 'AGO', 'NATIONAL_CORRESPONDENT');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (27, 'HTI', 'REVIEWER');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (37, 'KEN', 'REVIEWER');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (38, 'AFG', 'NATIONAL_CORRESPONDENT');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (39, 'ITA', 'REVIEWER');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (38, 'ITA', 'NATIONAL_CORRESPONDENT');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (40, 'FRA', 'NATIONAL_CORRESPONDENT');
INSERT INTO user_country_role (user_id, country_iso, role) VALUES (37, 'SRB', 'NATIONAL_CORRESPONDENT');
