-- This table holds information of exisitng schemas.
-- Each scehma is a new version of the database which has been "frozen"

CREATE TYPE fra_version_status AS ENUM (
  'pending',
  'running',
  'completed',
  'failed'
)

create TABLE fra_version(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by INTEGER REFERENCES fra_user(id),
  version_number VARCHAR(255) NOT NULL,
  status versioning_status NOT NULL,
  publish_time TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT Now() NOT NULL,
  updated_at TIMESTAMP DEFAULT Now() NOT NULL
);
