
INSERT INTO region
VALUES ('UNECE', 'unece');

INSERT INTO country_region
VALUES ('UNECE', 'ALB'),
       ('UNECE', 'AND'),
       ('UNECE', 'ARM'),
       ('UNECE', 'AUT'),
       ('UNECE', 'AZE'),
       ('UNECE', 'BLR'),
       ('UNECE', 'BEL'),
       ('UNECE', 'BIH'),
       ('UNECE', 'BGR'),
       ('UNECE', 'CAN'),
       ('UNECE', 'HRV'),
       ('UNECE', 'CYP'),
       ('UNECE', 'CZE'),
       ('UNECE', 'DNK'),
       ('UNECE', 'EST'),
       ('UNECE', 'FIN'),
       ('UNECE', 'FRA'),
       ('UNECE', 'GEO'),
       ('UNECE', 'DEU'),
       ('UNECE', 'GRC'),
       ('UNECE', 'HUN'),
       ('UNECE', 'ISL'),
       ('UNECE', 'IRL'),
       ('UNECE', 'ISR'),
       ('UNECE', 'ITA'),
       ('UNECE', 'KAZ'),
       ('UNECE', 'KGZ'),
       ('UNECE', 'LVA'),
       ('UNECE', 'LIE'),
       ('UNECE', 'LTU'),
       ('UNECE', 'LUX'),
       ('UNECE', 'MLT'),
       ('UNECE', 'MCO'),
       ('UNECE', 'MNE'),
       ('UNECE', 'NLD'),
       ('UNECE', 'MKD'),
       ('UNECE', 'NOR'),
       ('UNECE', 'POL'),
       ('UNECE', 'PRT'),
       ('UNECE', 'MDA'),
       ('UNECE', 'ROU'),
       ('UNECE', 'RUS'),
       ('UNECE', 'SMR'),
       ('UNECE', 'SRB'),
       ('UNECE', 'SVK'),
       ('UNECE', 'SVN'),
       ('UNECE', 'ESP'),
       ('UNECE', 'SWE'),
       ('UNECE', 'CHE'),
       ('UNECE', 'TJK'),
       ('UNECE', 'TUR'),
       ('UNECE', 'TKM'),
       ('UNECE', 'UKR'),
       ('UNECE', 'GBR'),
       ('UNECE', 'USA'),
       ('UNECE', 'UZB');
