
INSERT INTO region
VALUES ('ITTO', 'international_tropical_timber_organization');

INSERT INTO country_region
VALUES ('ITTO', 'AUS'),
       ('ITTO', 'AUT'),
       ('ITTO', 'BEL'),
       ('ITTO', 'BOL'),
       ('ITTO', 'BRA'),
       ('ITTO', 'KHM'),
       ('ITTO', 'CMR'),
       ('ITTO', 'CAN'),
       ('ITTO', 'CAF'),
       ('ITTO', 'CHN'),
       ('ITTO', 'COL'),
       ('ITTO', 'CIV'),
       ('ITTO', 'COD'),
       ('ITTO', 'DNK'),
       ('ITTO', 'ECU'),
       ('ITTO', 'EGY'),
       ('ITTO', 'FJI'),
       ('ITTO', 'FIN'),
       ('ITTO', 'FRA'),
       ('ITTO', 'GAB'),
       ('ITTO', 'DEU'),
       ('ITTO', 'GHA'),
       ('ITTO', 'GRC'),
       ('ITTO', 'GUY'),
       ('ITTO', 'HND'),
       ('ITTO', 'IND'),
       ('ITTO', 'IDN'),
       ('ITTO', 'IRL'),
       ('ITTO', 'ITA'),
       ('ITTO', 'JPN'),
       ('ITTO', 'LBR'),
       ('ITTO', 'MYS'),
       ('ITTO', 'MMR'),
       ('ITTO', 'NPL'),
       ('ITTO', 'NLD'),
       ('ITTO', 'NZL'),
       ('ITTO', 'NOR'),
       ('ITTO', 'PAN'),
       ('ITTO', 'PNG'),
       ('ITTO', 'PER'),
       ('ITTO', 'PHL'),
       ('ITTO', 'COG'),
       ('ITTO', 'KOR'),
       ('ITTO', 'ESP'),
       ('ITTO', 'SUR'),
       ('ITTO', 'SWE'),
       ('ITTO', 'CHE'),
       ('ITTO', 'THA'),
       ('ITTO', 'TGO'),
       ('ITTO', 'GBR'),
       ('ITTO', 'USA'),
       ('ITTO', 'VEN');
