module.exports = {
  '1a_forestArea': 'Area (1000 ha)',
  '1a_otherWoodedLand': 'Area (1000 ha)',
  '1a_landArea': 'Area (1000 ha)',
  '1b_naturallyRegeneratingForest': 'Forest area (1000 ha)',
  '1b_plantedForest': 'Forest area (1000 ha)',
  '1b_plantationForest': 'Forest area (1000 ha)',
  '1b_plantationForestIntroduced': 'Forest area (1000 ha)',
  '1b_otherPlantedForest': 'Forest area (1000 ha)',
  '1e_bamboos': 'Area (1000 ha)',
  '1e_mangroves': 'Area (1000 ha)',
  '1e_tempUnstocked': 'Area (1000 ha)',
  '1e_primary': 'Area (1000 ha)',
  '1e_rubber': 'Area (1000 ha)',
  '1f_palms': 'Area (1000 ha)',
  '1f_treeOrchards': 'Area (1000 ha)',
  '1f_agroforestry': 'Area (1000 ha)',
  '1f_treesUrbanSettings': 'Area (1000 ha)',
  '1f_other': 'Area (1000 ha)',
  '2a_gs_ha_nat_reg': 'Growing stock m³/ha (over bark)',
  '2a_gs_ha_planted': 'Growing stock m³/ha (over bark)',
  '2a_gs_ha_plantation': 'Growing stock m³/ha (over bark)',
  '2a_gs_ha_other_planted': 'Growing stock m³/ha (over bark)',
  '2a_gs_ha_forest': 'Growing stock m³/ha (over bark)',
  '2a_gs_ha_owl': 'Growing stock m³/ha (over bark)',
  '2a_gs_tot_nat_reg': 'Total growing stock (million m³ over bark)',
  '2a_gs_tot_planted': 'Total growing stock (million m³ over bark)',
  '2a_gs_tot_plantation': 'Total growing stock (million m³ over bark)',
  '2a_gs_tot_other_planted': 'Total growing stock (million m³ over bark)',
  '2a_gs_tot_forest': 'Total growing stock (million m³ over bark)',
  '2a_gs_tot_owl': 'Total growing stock (million m³ over bark)',
  '2b_native_#1': 'Growing stock in forest (million m³ over bark)',
  '2b_native_#2': 'Growing stock in forest (million m³ over bark)',
  '2b_native_#3': 'Growing stock in forest (million m³ over bark)',
  '2b_native_#4': 'Growing stock in forest (million m³ over bark)',
  '2b_native_#5': 'Growing stock in forest (million m³ over bark)',
  '2b_native_#6': 'Growing stock in forest (million m³ over bark)',
  '2b_native_#7': 'Growing stock in forest (million m³ over bark)',
  '2b_native_#8': 'Growing stock in forest (million m³ over bark)',
  '2b_native_#9': 'Growing stock in forest (million m³ over bark)',
  '2b_native_#10': 'Growing stock in forest (million m³ over bark)',
  '2b_native_remaining': 'Growing stock in forest (million m³ over bark)',
  '2b_native_total': 'Growing stock in forest (million m³ over bark)',
  '2b_introduced_#1': 'Growing stock in forest (million m³ over bark)',
  '2b_introduced_#2': 'Growing stock in forest (million m³ over bark)',
  '2b_introduced_#3': 'Growing stock in forest (million m³ over bark)',
  '2b_introduced_#4': 'Growing stock in forest (million m³ over bark)',
  '2b_introduced_#5': 'Growing stock in forest (million m³ over bark)',
  '2b_introduced_remaining': 'Growing stock in forest (million m³ over bark)',
  '2b_introduced_total': 'Growing stock in forest (million m³ over bark)',
  '2b_total_gs': 'Growing stock in forest (million m³ over bark)',
  '2c_agb': 'Forest biomass (tonnes/ha)',
  '2c_bgb': 'Forest biomass (tonnes/ha)',
  '2c_dwb': 'Forest biomass (tonnes/ha)',
  '2d_carbon_agb': 'Forest carbon (tonnes/ha)',
  '2d_carbon_bgb': 'Forest carbon (tonnes/ha)',
  '2d_carbon_dw': 'Forest carbon (tonnes/ha)',
  '2d_carbon_litter': 'Forest carbon (tonnes/ha)',
  '2d_carbon_soil': 'Forest carbon (tonnes/ha)',
  '2d_soil_depth_cm': 'Forest carbon (tonnes/ha)',
  '3a_prim_prod': 'Forest area (1000 ha)',
  '3a_prim_prot': 'Forest area (1000 ha)',
  '3a_prim_biodiv': 'Forest area (1000 ha)',
  '3a_prim_socserv': 'Forest area (1000 ha)',
  '3a_prim_multi': 'Forest area (1000 ha)',
  '3a_prim_other': 'Forest area (1000 ha)',
  '3a_prim_no_unknown': 'Forest area (1000 ha)',
  '3a_tot_prod': 'Forest area (1000 ha)',
  '3a_tot_prot': 'Forest area (1000 ha)',
  '3a_tot_biodiv': 'Forest area (1000 ha)',
  '3a_tot_socserv': 'Forest area (1000 ha)',
  '3a_tot_other': 'Forest area (1000 ha)',
  '3b_protected': 'Area (1000 ha)',
  '3b_forMngt': 'Area (1000 ha)',
  '3b_mngtProt': 'Area (1000 ha)',
  '4a_priv_own': 'Forest area (1000 ha)',
  '4a_individ': 'Forest area (1000 ha)',
  '4a_bus_inst': 'Forest area (1000 ha)',
  '4a_indigenous': 'Forest area (1000 ha)',
  '4a_pub_own': 'Forest area (1000 ha)',
  '4a_unknown': 'Forest area (1000 ha)',
  '4b_pub_admin': 'Forest area (1000 ha)',
  '4b_individuals': 'Forest area (1000 ha)',
  '4b_bus_inst': 'Forest area (1000 ha)',
  '4b_indigenous': 'Forest area (1000 ha)',
  '4b_unknown': 'Forest area (1000 ha)',
  '5c_y_n': 'Area (1000 ha)',
  '6a_policies_national': 'Area (1000 ha)',
  '6a_policies_sub_national': 'Area (1000 ha)',
  '6a_legislation_national': 'Area (1000 ha)',
  '6a_legislation_sub_national': 'Area (1000 ha)',
  '6a_platform_national': 'Area (1000 ha)',
  '6a_platform_sub_national': 'Area (1000 ha)',
  '6a_traceability_national': 'Area (1000 ha)',
  '6a_traceability_sub_national': 'Area (1000 ha)',
  '6b_pfe_y_n': '',
  '6b_pfe_area': 'Forest area (1000 ha)',
  '7a_employment_tot': 'Full-time equivalents (1000 FTE)',
  '7a_employment_fem': 'Full-time equivalents (1000 FTE)',
  '7a_employment_male': 'Full-time equivalents (1000 FTE)',
  '7a_emp_forestry_tot': 'Full-time equivalents (1000 FTE)',
  '7a_emp_forestry_fem': 'Full-time equivalents (1000 FTE)',
  '7a_emp_forestry_male': 'Full-time equivalents (1000 FTE)',
  '7a_emp_logging_tot': 'Full-time equivalents (1000 FTE)',
  '7a_emp_logging_fem': 'Full-time equivalents (1000 FTE)',
  '7a_emp_logging_male': 'Full-time equivalents (1000 FTE)',
  '7a_emp_nwfp_tot': 'Full-time equivalents (1000 FTE)',
  '7a_emp_nwfp_fem': 'Full-time equivalents (1000 FTE)',
  '7a_emp_nwfp_male': 'Full-time equivalents (1000 FTE)',
  '7a_emp_support_tot': 'Full-time equivalents (1000 FTE)',
  '7a_emp_support_fem': 'Full-time equivalents (1000 FTE)',
  '7a_emp_support_male': 'Full-time equivalents (1000 FTE)',
  '7b_phd_tot': '',
  '7b_phd_fem': '',
  '7b_phd_male': '',
  '7b_msc_tot': '',
  '7b_msc_fem': '',
  '7b_msc_male': '',
  '7b_ba_tot': '',
  '7b_ba_fem': '',
  '7b_ba_male': '',
  '7b_tech_tot': '',
  '7b_tech_fem': '',
  '7b_tech_male': '',
  '7b_total_tot': '',
  '7b_total_fem': '',
  '7b_total_male': ''
}
