pull_request_rules:
  - name: Automatic merge all but production
    conditions:
      - and:
        - "#approved-reviews-by>=1"
        - base!=production
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
  - name: Automatic merge production
    conditions:
      - and:
        - "#approved-reviews-by>=1"
        - base=production
    actions:
      merge:
        method: merge
        strict: smart+fasttrack        
  - name: Automatic branch update
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
      - head!=master
    actions:
      update: {}
  - name: Delete head branch after merge
    conditions:
      - and:
        - merged
        - head!=production
        - head!=master
    actions:
      delete_head_branch: {}
