pull_request_rules:
  - name: Automatic merge using squash
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      queue:
        method: squash
  - name: Automatic branch update
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
      - head!=production
      - head!=staging
    actions:
      update: {}
  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: 
        force: true
