queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"
pull_request_rules:
  - name: Automatic merge
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      queue:
        method: squash
        name: default
  - name: Automatic branch update
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
      - head!=master
    actions:
      update: {}
  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: 
        force: true
