pull_request_rules:
  - name: Automatic merge all but production
    conditions:
      - and:
        - "#approved-reviews-by>=1"
        - base!=production"
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
  - name: Automatic merge production
    conditions:
      - and:
        - "#approved-reviews-by>=1"
        - base=production"
    actions:
      merge:
        method: merge
        strict: smart+fasttrack        
  - name: automatic branch update
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
    actions:
      update: {}
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
