module.exports = {
  tableName: 'table_4_4c',
  schemaName: 'pan_european',
  section: 'panEuropean_4_4_c',
  rows: {
    names: [
      '_01',
      '_02',
      '_03',
      '_04',
      '_05',
      '_06',
      '_07',
      '_08',
      '_09',
      '_10',
      '_11',
      '_12',
      '_13',
      '_14',
      '_15',
      '_16',
      '_17',
      '_18',
      '_19',
      '_20',
    ],
  },
  columns: [
    { name: 'scientific_name_of_invasive_tree_species', type: 'text' },
    { name: 'forest_area_affected_2005', type: 'numeric' },
    { name: 'forest_area_affected_2010', type: 'numeric' },
    { name: 'forest_area_affected_2015', type: 'numeric' },
  ],
}
