export default {
  tableName: 'table_6_8',
  schemaName: 'pan_european',
  section: 'panEuropean_6_8',
  rows: {
    names: [
      'exports_of_forest_products_quantity',
      'exports_of_forest_products_value',
      'import * as s_of_forest_products_quantity',
      'import * as s_of_forest_products_value',
    ],
  },
  columns: [
    { name: '_1992', type: 'numeric' },
    { name: '_1993', type: 'numeric' },
    { name: '_1994', type: 'numeric' },
    { name: '_1995', type: 'numeric' },
    { name: '_1996', type: 'numeric' },
    { name: '_1997', type: 'numeric' },
    { name: '_1998', type: 'numeric' },
    { name: '_1999', type: 'numeric' },
    { name: '_2000', type: 'numeric' },
    { name: '_2001', type: 'numeric' },
    { name: '_2002', type: 'numeric' },
    { name: '_2003', type: 'numeric' },
    { name: '_2004', type: 'numeric' },
    { name: '_2005', type: 'numeric' },
    { name: '_2006', type: 'numeric' },
    { name: '_2007', type: 'numeric' },
    { name: '_2008', type: 'numeric' },
    { name: '_2009', type: 'numeric' },
    { name: '_2010', type: 'numeric' },
    { name: '_2011', type: 'numeric' },
    { name: '_2012', type: 'numeric' },
    { name: '_2013', type: 'numeric' },
    { name: '_2014', type: 'numeric' },
    { name: '_2015', type: 'numeric' },
    { name: '_2016', type: 'numeric' },
    { name: '_2017', type: 'numeric' },
  ],
}
