module.exports = {
  tableName: 'table_1_2c',
  schemaName: 'pan_european',
  section: 'panEuropean_1_2_c',
  rows: {
    names: [
      'no1_ranked_in_terms_of_volume',
      'no2_ranked_in_terms_of_volume',
      'no3_ranked_in_terms_of_volume',
      'no4_ranked_in_terms_of_volume',
      'no5_ranked_in_terms_of_volume',
      'no6_ranked_in_terms_of_volume',
      'no7_ranked_in_terms_of_volume',
      'no8_ranked_in_terms_of_volume',
      'no9_ranked_in_terms_of_volume',
      'no10_ranked_in_terms_of_volume',
      'remaining',
      'total',
    ],
  },
  columns: [
    { name: 'scientific_name', type: 'text' },
    { name: 'common_name', type: 'text' },
    { name: 'growing_stock_in_forest_1990', type: 'numeric' },
    { name: 'growing_stock_in_forest_2000', type: 'numeric' },
    { name: 'growing_stock_in_forest_2005', type: 'numeric' },
    { name: 'growing_stock_in_forest_2010', type: 'numeric' },
    { name: 'growing_stock_in_forest_2015', type: 'numeric' },
    { name: 'growing_stock_in_forest_2020', type: 'numeric' },
  ],
}
