export default {
  tableName: 'disturbances',
  rows: {
    names: ['insects', 'diseases', 'severe_weather_events', 'other'],
  },
  columns: [
    { name: '2000', type: 'numeric' },
    { name: '2001', type: 'numeric' },
    { name: '2002', type: 'numeric' },
    { name: '2003', type: 'numeric' },
    { name: '2004', type: 'numeric' },
    { name: '2005', type: 'numeric' },
    { name: '2006', type: 'numeric' },
    { name: '2007', type: 'numeric' },
    { name: '2008', type: 'numeric' },
    { name: '2009', type: 'numeric' },
    { name: '2010', type: 'numeric' },
    { name: '2011', type: 'numeric' },
    { name: '2012', type: 'numeric' },
    { name: '2013', type: 'numeric' },
    { name: '2014', type: 'numeric' },
    { name: '2015', type: 'numeric' },
    { name: '2016', type: 'numeric' },
    { name: '2017', type: 'numeric' },
  ],
}
