insert into country(country_iso,name) values('AFG','Afghanistan');
insert into country(country_iso,name) values('ALB','Albania');
insert into country(country_iso,name) values('DZA','Algeria');
insert into country(country_iso,name) values('AND','Andorra');
insert into country(country_iso,name) values('AGO','Angola');
insert into country(country_iso,name) values('ATG','Antigua and Barbuda');
insert into country(country_iso,name) values('ARG','Argentina');
insert into country(country_iso,name) values('ARM','Armenia');
insert into country(country_iso,name) values('AUS','Australia');
insert into country(country_iso,name) values('AUT','Austria');
insert into country(country_iso,name) values('AZE','Azerbaijan');
insert into country(country_iso,name) values('BHS','Bahamas');
insert into country(country_iso,name) values('BHR','Bahrain');
insert into country(country_iso,name) values('BGD','Bangladesh');
insert into country(country_iso,name) values('BRB','Barbados');
insert into country(country_iso,name) values('BLR','Belarus');
insert into country(country_iso,name) values('BEL','Belgium');
insert into country(country_iso,name) values('BLZ','Belize');
insert into country(country_iso,name) values('BEN','Benin');
insert into country(country_iso,name) values('BTN','Bhutan');
insert into country(country_iso,name) values('BOL','Bolivia (Plurinational State of)');
insert into country(country_iso,name) values('BIH','Bosnia and Herzegovina');
insert into country(country_iso,name) values('BWA','Botswana');
insert into country(country_iso,name) values('BRA','Brazil');
insert into country(country_iso,name) values('BRN','Brunei Darussalam');
insert into country(country_iso,name) values('BGR','Bulgaria');
insert into country(country_iso,name) values('BFA','Burkina Faso');
insert into country(country_iso,name) values('BDI','Burundi');
insert into country(country_iso,name) values('CPV','Cabo Verde');
insert into country(country_iso,name) values('KHM','Cambodia');
insert into country(country_iso,name) values('CMR','Cameroon');
insert into country(country_iso,name) values('CAN','Canada');
insert into country(country_iso,name) values('CAF','Central African Republic');
insert into country(country_iso,name) values('TCD','Chad');
insert into country(country_iso,name) values('CHL','Chile');
insert into country(country_iso,name) values('CHN','China');
insert into country(country_iso,name) values('COL','Colombia');
insert into country(country_iso,name) values('COM','Comoros');
insert into country(country_iso,name) values('COG','Congo');
insert into country(country_iso,name) values('COK','Cook Islands');
insert into country(country_iso,name) values('CRI','Costa Rica');
insert into country(country_iso,name) values('HRV','Croatia');
insert into country(country_iso,name) values('CUB','Cuba');
insert into country(country_iso,name) values('CYP','Cyprus');
insert into country(country_iso,name) values('CZE','Czechia');
insert into country(country_iso,name) values('CIV','Côte d''Ivoire');
insert into country(country_iso,name) values('PRK','Democratic People''s Republic of Korea');
insert into country(country_iso,name) values('COD','Democratic Republic of the Congo');
insert into country(country_iso,name) values('DNK','Denmark');
insert into country(country_iso,name) values('DJI','Djibouti');
insert into country(country_iso,name) values('DMA','Dominica');
insert into country(country_iso,name) values('DOM','Dominican Republic');
insert into country(country_iso,name) values('ECU','Ecuador');
insert into country(country_iso,name) values('EGY','Egypt');
insert into country(country_iso,name) values('SLV','El Salvador');
insert into country(country_iso,name) values('GNQ','Equatorial Guinea');
insert into country(country_iso,name) values('ERI','Eritrea');
insert into country(country_iso,name) values('EST','Estonia');
insert into country(country_iso,name) values('ETH','Ethiopia');
insert into country(country_iso,name) values('FRO','Faroe Islands (Associate Member)');
insert into country(country_iso,name) values('FJI','Fiji');
insert into country(country_iso,name) values('FIN','Finland');
insert into country(country_iso,name) values('FRA','France');
insert into country(country_iso,name) values('GAB','Gabon');
insert into country(country_iso,name) values('GMB','Gambia');
insert into country(country_iso,name) values('GEO','Georgia');
insert into country(country_iso,name) values('DEU','Germany');
insert into country(country_iso,name) values('GHA','Ghana');
insert into country(country_iso,name) values('GRC','Greece');
insert into country(country_iso,name) values('GRD','Grenada');
insert into country(country_iso,name) values('GTM','Guatemala');
insert into country(country_iso,name) values('GIN','Guinea');
insert into country(country_iso,name) values('GNB','Guinea-Bissau');
insert into country(country_iso,name) values('GUY','Guyana');
insert into country(country_iso,name) values('HTI','Haiti');
insert into country(country_iso,name) values('HND','Honduras');
insert into country(country_iso,name) values('HUN','Hungary');
insert into country(country_iso,name) values('ISL','Iceland');
insert into country(country_iso,name) values('IND','India');
insert into country(country_iso,name) values('IDN','Indonesia');
insert into country(country_iso,name) values('IRN','Iran (Islamic Republic of)');
insert into country(country_iso,name) values('IRQ','Iraq');
insert into country(country_iso,name) values('IRL','Ireland');
insert into country(country_iso,name) values('ISR','Israel');
insert into country(country_iso,name) values('ITA','Italy');
insert into country(country_iso,name) values('JAM','Jamaica');
insert into country(country_iso,name) values('JPN','Japan');
insert into country(country_iso,name) values('JOR','Jordan');
insert into country(country_iso,name) values('KAZ','Kazakhstan');
insert into country(country_iso,name) values('KEN','Kenya');
insert into country(country_iso,name) values('KIR','Kiribati');
insert into country(country_iso,name) values('KWT','Kuwait');
insert into country(country_iso,name) values('KGZ','Kyrgyzstan');
insert into country(country_iso,name) values('LAO','Lao People''s Democratic Republic');
insert into country(country_iso,name) values('LVA','Latvia');
insert into country(country_iso,name) values('LBN','Lebanon');
insert into country(country_iso,name) values('LSO','Lesotho');
insert into country(country_iso,name) values('LBR','Liberia');
insert into country(country_iso,name) values('LBY','Libya');
insert into country(country_iso,name) values('LTU','Lithuania');
insert into country(country_iso,name) values('LUX','Luxembourg');
insert into country(country_iso,name) values('MDG','Madagascar');
insert into country(country_iso,name) values('MWI','Malawi');
insert into country(country_iso,name) values('MYS','Malaysia');
insert into country(country_iso,name) values('MDV','Maldives');
insert into country(country_iso,name) values('MLI','Mali');
insert into country(country_iso,name) values('MLT','Malta');
insert into country(country_iso,name) values('MHL','Marshall Islands');
insert into country(country_iso,name) values('MRT','Mauritania');
insert into country(country_iso,name) values('MUS','Mauritius');
insert into country(country_iso,name) values('MEX','Mexico');
insert into country(country_iso,name) values('FSM','Micronesia (Federated States of)');
insert into country(country_iso,name) values('MCO','Monaco');
insert into country(country_iso,name) values('MNG','Mongolia');
insert into country(country_iso,name) values('MNE','Montenegro');
insert into country(country_iso,name) values('MAR','Morocco');
insert into country(country_iso,name) values('MOZ','Mozambique');
insert into country(country_iso,name) values('MMR','Myanmar');
insert into country(country_iso,name) values('NAM','Namibia');
insert into country(country_iso,name) values('NRU','Nauru');
insert into country(country_iso,name) values('NPL','Nepal');
insert into country(country_iso,name) values('NLD','Netherlands');
insert into country(country_iso,name) values('NZL','New Zealand');
insert into country(country_iso,name) values('NIC','Nicaragua');
insert into country(country_iso,name) values('NER','Niger');
insert into country(country_iso,name) values('NGA','Nigeria');
insert into country(country_iso,name) values('NIU','Niue');
insert into country(country_iso,name) values('NOR','Norway');
insert into country(country_iso,name) values('OMN','Oman');
insert into country(country_iso,name) values('PAK','Pakistan');
insert into country(country_iso,name) values('PLW','Palau');
insert into country(country_iso,name) values('PAN','Panama');
insert into country(country_iso,name) values('PNG','Papua New Guinea');
insert into country(country_iso,name) values('PRY','Paraguay');
insert into country(country_iso,name) values('PER','Peru');
insert into country(country_iso,name) values('PHL','Philippines');
insert into country(country_iso,name) values('POL','Poland');
insert into country(country_iso,name) values('PRT','Portugal');
insert into country(country_iso,name) values('QAT','Qatar');
insert into country(country_iso,name) values('KOR','Republic of Korea');
insert into country(country_iso,name) values('MDA','Republic of Moldova');
insert into country(country_iso,name) values('ROU','Romania');
insert into country(country_iso,name) values('RUS','Russian Federation');
insert into country(country_iso,name) values('RWA','Rwanda');
insert into country(country_iso,name) values('KNA','Saint Kitts and Nevis');
insert into country(country_iso,name) values('LCA','Saint Lucia');
insert into country(country_iso,name) values('VCT','Saint Vincent and the Grenadines');
insert into country(country_iso,name) values('WSM','Samoa');
insert into country(country_iso,name) values('SMR','San Marino');
insert into country(country_iso,name) values('STP','Sao Tome and Principe');
insert into country(country_iso,name) values('SAU','Saudi Arabia');
insert into country(country_iso,name) values('SEN','Senegal');
insert into country(country_iso,name) values('SRB','Serbia');
insert into country(country_iso,name) values('SYC','Seychelles');
insert into country(country_iso,name) values('SLE','Sierra Leone');
insert into country(country_iso,name) values('SGP','Singapore');
insert into country(country_iso,name) values('SVK','Slovakia');
insert into country(country_iso,name) values('SVN','Slovenia');
insert into country(country_iso,name) values('SLB','Solomon Islands');
insert into country(country_iso,name) values('SOM','Somalia');
insert into country(country_iso,name) values('ZAF','South Africa');
insert into country(country_iso,name) values('SSD','South Sudan');
insert into country(country_iso,name) values('ESP','Spain');
insert into country(country_iso,name) values('LKA','Sri Lanka');
insert into country(country_iso,name) values('SDN','Sudan');
insert into country(country_iso,name) values('SUR','Suriname');
insert into country(country_iso,name) values('SWZ','Swaziland');
insert into country(country_iso,name) values('SWE','Sweden');
insert into country(country_iso,name) values('CHE','Switzerland');
insert into country(country_iso,name) values('SYR','Syrian Arab Republic');
insert into country(country_iso,name) values('TJK','Tajikistan');
insert into country(country_iso,name) values('THA','Thailand');
insert into country(country_iso,name) values('MKD','The former Yugoslav Republic of Macedonia');
insert into country(country_iso,name) values('TLS','Timor-Leste');
insert into country(country_iso,name) values('TGO','Togo');
insert into country(country_iso,name) values('TKL','Tokelau (Associate Member)');
insert into country(country_iso,name) values('TON','Tonga');
insert into country(country_iso,name) values('TTO','Trinidad and Tobago');
insert into country(country_iso,name) values('TUN','Tunisia');
insert into country(country_iso,name) values('TUR','Turkey');
insert into country(country_iso,name) values('TKM','Turkmenistan');
insert into country(country_iso,name) values('TUV','Tuvalu');
insert into country(country_iso,name) values('UGA','Uganda');
insert into country(country_iso,name) values('UKR','Ukraine');
insert into country(country_iso,name) values('ARE','United Arab Emirates');
insert into country(country_iso,name) values('GBR','United Kingdom');
insert into country(country_iso,name) values('TZA','United Republic of Tanzania');
insert into country(country_iso,name) values('USA','United States of America');
insert into country(country_iso,name) values('URY','Uruguay');
insert into country(country_iso,name) values('UZB','Uzbekistan');
insert into country(country_iso,name) values('VUT','Vanuatu');
insert into country(country_iso,name) values('VEN','Venezuela (Bolivarian Republic of)');
insert into country(country_iso,name) values('VNM','Viet Nam');
insert into country(country_iso,name) values('YEM','Yemen');
insert into country(country_iso,name) values('ZMB','Zambia');
insert into country(country_iso,name) values('ZWE','Zimbabwe');