ALTER TABLE
country ADD COLUMN country_iso2 CHARACTER VARYING(2);
ALTER TABLE
country ADD COLUMN list_name_en CHARACTER VARYING;
ALTER TABLE
country ADD COLUMN full_name_en CHARACTER VARYING;
ALTER TABLE
country ADD COLUMN list_name_es CHARACTER VARYING;
ALTER TABLE
country ADD COLUMN full_name_es CHARACTER VARYING;
ALTER TABLE
country ADD COLUMN list_name_fr CHARACTER VARYING;
ALTER TABLE
country ADD COLUMN full_name_fr CHARACTER VARYING;
ALTER TABLE
country ADD COLUMN list_name_ru CHARACTER VARYING;
ALTER TABLE
country ADD COLUMN full_name_ru CHARACTER VARYING;
