INSERT INTO region
VALUES ('EU27', 'eu-27');

INSERT INTO country_region
VALUES ('EU27', 'AUT'),
        ('EU27', 'BEL'),
        ('EU27', 'BGR'),
        ('EU27', 'HRV'),
        ('EU27', 'CYP'),
        ('EU27', 'CZE'),
        ('EU27', 'DNK'),
        ('EU27', 'EST'),
        ('EU27', 'FIN'),
        ('EU27', 'FRA'),
        ('EU27', 'DEU'),
        ('EU27', 'GRC'),
        ('EU27', 'HUN'),
        ('EU27', 'IRL'),
        ('EU27', 'ITA'),
        ('EU27', 'LVA'),
        ('EU27', 'LTU'),
        ('EU27', 'LUX'),
        ('EU27', 'MLT'),
        ('EU27', 'NLD'),
        ('EU27', 'POL'),
        ('EU27', 'PRT'),
        ('EU27', 'ROU'),
        ('EU27', 'SVK'),
        ('EU27', 'SVN'),
        ('EU27', 'ESP'),
        ('EU27', 'SWE');