FROM node:24.15.0-slim

RUN apt-get update && apt-get install -y \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN rm -rf /usr/local/bin/yarn \
    && rm -rf /usr/local/bin/yarnpkg \
    && npm install -g yarn@1.22.22

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

RUN yarn playwright install --with-deps chromium

COPY . .

EXPOSE 9323

CMD ["yarn", "test:e2e"]
