FROM node:22.18.0

RUN rm -rf /usr/local/bin/yarn \
    && rm -rf /usr/local/bin/yarnpkg \
    && npm install -g yarn@1.22.22

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .
RUN yarn build

EXPOSE 9001
CMD ["yarn", "start"]
