const express = require('express')

const eofApi = require('./eof/api')
const odpApi = require('./odp/api')
const userApi = require('./user/userApi')
const traditionalTableApi = require('./traditionalTable/api')
const descriptionsApi = require('./descriptions/api')
const reviewApi = require('./review/api')
const countryApi = require('./country/api')
const assessmentApi = require('./assessment/api')
const growingStockApi = require('./growingStock/growingStockApi')
const biomassStockApi = require('./biomassStock/biomassStockApi')
const auditApi = require('./audit/api')
const sustainableDevelopmentApi = require('./sustainableDevelopment/sustainableDevelopmentApi')
const panEuropeanApi = require('./panEuropean/panEuropeanApi')
const landingApi = require('./landing/landingApi')
const userChatApi = require('./userChat/userChatApi')
const fileRepositoryApi = require('./fileRepository/fileRepositoryApi')
const collaboratorsApi = require('./collaborators/collaboratorsApi')
const countryMessageBoardApi = require('./countryMessageBoard/countryMessageBoardApi')
const versioningApi = require('./versioning/api')
const statisticalFactsheetsApi = require('./statisticalFactsheets/api')
const dataExportApi = require('./dataExport/api')

const apiRouter = express.Router()
// Nothing should be cached by default with the APIs
apiRouter.use((req, res, next) => {
  res.set('Cache-Control', 'no-store')
  next()
})

userApi.init(apiRouter)
countryApi.init(apiRouter)
odpApi.init(apiRouter)
eofApi.init(apiRouter)
traditionalTableApi.init(apiRouter)
descriptionsApi.init(apiRouter)
reviewApi.init(apiRouter)
assessmentApi.init(apiRouter)
growingStockApi.init(apiRouter)
biomassStockApi.init(apiRouter)
auditApi.init(apiRouter)
sustainableDevelopmentApi.init(apiRouter)
panEuropeanApi.init(apiRouter)
landingApi.init(apiRouter)
userChatApi.init(apiRouter)
fileRepositoryApi.init(apiRouter)
collaboratorsApi.init(apiRouter)
countryMessageBoardApi.init(apiRouter)
versioningApi.init(apiRouter)
statisticalFactsheetsApi.init(apiRouter)
dataExportApi.init(apiRouter)

module.exports.router = apiRouter
