const variables = {
  // 1a
  forest_area: 'forest_area',
  total_land_area: 'total_land_area',
  forest_area_percent: 'forest_area_percent',
  other_wooded_land: 'other_wooded_land',
  // 1b
  plantation_forest_introduced_area: 'plantation_forest_introduced_area',
  planted_forest: 'planted_forest',
  other_planted_forest_area: 'other_planted_forest_area',
  natural_forest_area: 'natural_forest_area',
  plantation_forest_area: 'plantation_forest_area',
  // 1c
  afforestation: 'afforestation',
  deforestation: 'deforestation',
  forest_area_net_change: 'forest_area_net_change',
  forest_expansion: 'forest_expansion',
  natural_expansion: 'natural_expansion',
  // 1d
  reforestation: 'reforestation',
  // 1e
  bamboo: 'bamboo',
  mangroves: 'mangroves',
  temporarily_unstocked: 'temporarily_unstocked',
  primary_forest: 'primary_forest',
  rubber_wood: 'rubber_wood',
  // 1f
  palms: 'palms',
  tree_orchards: 'tree_orchards',
  agroforestry: 'agroforestry',
  trees_in_urban_settings: 'trees_in_urban_settings',
  other: 'other',

  // 2a
  naturally_regenerating_forest: 'naturally_regenerating_forest',
  plantation_forest: 'plantation_forest',
  other_planted_forest: 'other_planted_forest',
  // other_wooded_land: 'other_wooded_land',
  // planted_forest: 'planted_forest',
  forest: 'forest',
  // 2b
  introduced_rank1: 'introduced_rank1',
  introduced_rank2: 'introduced_rank2',
  introduced_rank3: 'introduced_rank3',
  introduced_rank4: 'introduced_rank4',
  introduced_rank5: 'introduced_rank5',
  introduced_tree_species_heading_placeholder: 'introduced_tree_species_heading_placeholder',
  native_rank1: 'native_rank1',
  native_rank10: 'native_rank10',
  native_rank2: 'native_rank2',
  native_rank3: 'native_rank3',
  native_rank4: 'native_rank4',
  native_rank5: 'native_rank5',
  native_rank6: 'native_rank6',
  native_rank7: 'native_rank7',
  native_rank8: 'native_rank8',
  native_rank9: 'native_rank9',
  remaining_introduced_placeholder: 'remaining_introduced_placeholder',
  remaining_native: 'remaining_native',
  total_native: 'total_native',
  total_remaining: 'total_remaining',
  // 2c
  forest_above_ground: 'forest_above_ground',
  forest_below_ground: 'forest_below_ground',
  forest_deadwood: 'forest_deadwood',
  // 2d
  carbon_stock_total: 'carbon_stock_total',
  carbon_forest_above_ground: 'carbon_forest_above_ground',
  carbon_stock_biomass_total: 'carbon_stock_biomass_total',
  carbon_forest_deadwood: 'carbon_forest_deadwood',
  carbon_forest_litter: 'carbon_forest_litter',
  carbon_forest_below_ground: 'carbon_forest_below_ground',
  carbon_forest_soil: 'carbon_forest_soil',
  // 3a
  production: 'production',
  protection_of_soil_and_water: 'protection_of_soil_and_water',
  conservation_of_biodiversity: 'conservation_of_biodiversity',
  social_services: 'social_services',
  multiple_use: 'multiple_use',
  no_unknown: 'no_unknown',
  // 3b
  forest_area_within_protected_areas: 'forest_area_within_protected_areas',
  forest_area_with_long_term_management_plan: 'forest_area_with_long_term_management_plan',
  of_which_in_protected_areas: 'of_which_in_protected_areas',
  // 4a
  private_ownership: 'private_ownership',
  of_which_by_individuals: 'of_which_by_individuals',
  of_which_by_private_businesses: 'of_which_by_private_businesses',
  of_which_by_communities: 'of_which_by_communities',
  public_ownership: 'public_ownership',
  other_or_unknown: 'other_or_unknown',
  // 4b
  communities: 'communities',
  individuals: 'individuals',
  private_businesses: 'private_businesses',
  public_administration: 'public_administration',
  // 5a
  insects: 'insects',
  diseases: 'diseases',
  severe_weather_events: 'severe_weather_events',
  // 5b
  total_land_area_affected_by_fire: 'total_land_area_affected_by_fire',
  of_which_on_forest: 'of_which_on_forest',
  // 5c
  does_country_monitor: 'does_country_monitor',
  national_definition: 'national_definition',
  how_monitored: 'how_monitored',
  // 6a
  policies_supporting_SFM: 'policies_supporting_SFM',
  legislations_supporting_SFM: 'legislations_supporting_SFM',
  platform_for_stakeholder_participation: 'platform_for_stakeholder_participation',
  existence_of_traceability_system: 'existence_of_traceability_system',
  // 6b
  area_of_permanent_forest_estate: 'area_of_permanent_forest_estate',
  // 7a
  employment_in_forestry_and_logging: 'employment_in_forestry_and_logging',
  of_which_silviculture_and_other_forestry_activities: 'of_which_silviculture_and_other_forestry_activities',
  of_which_logging: 'of_which_logging',
  of_which_gathering_of_non_wood_forest_products: 'of_which_gathering_of_non_wood_forest_products',
  of_which_support_services_to_forestry: 'of_which_support_services_to_forestry',
  // 7b
  doctoral_degree: 'doctoral_degree',
  masters_degree: 'masters_degree',
  bachelors_degree: 'bachelors_degree',
  technician_certificate: 'technician_certificate',
  total: 'total',
}

export default variables
