export default {
  tableName: 'table_6_10d',
  schemaName: 'pan_european',
  section: 'panEuropean_6_10_d',
  rows: {
    names: [
      'no1_area_available_for_public_recreation',
      'no2_area_available_for_public_recreation',
      'no3_area_available_for_public_recreation',
      'no4_area_available_for_public_recreation',
      'no5_area_available_for_public_recreation',
      'no6_area_available_for_public_recreation',
      'no7_area_available_for_public_recreation',
      'no8_area_available_for_public_recreation',
      'no9_area_available_for_public_recreation',
      'no10_area_available_for_public_recreation',
      'no11_area_available_for_public_recreation',
      'no12_area_available_for_public_recreation',
      'no13_area_available_for_public_recreation',
      'no14_area_available_for_public_recreation',
      'no15_area_available_for_public_recreation',
      'no16_area_available_for_public_recreation',
      'no17_area_available_for_public_recreation',
      'no18_area_available_for_public_recreation',
      'no19_area_available_for_public_recreation',
      'no20_area_available_for_public_recreation',
    ],
  },
  columns: [
    { name: 'facility', type: 'text' },
    { name: 'measurement_unit', type: 'text' },
    { name: 'extent_multiplicity', type: 'numeric' },
    { name: 'facility_category', type: 'text' },
  ],
}
