export enum UnitName {
  absoluteNumber = 'absoluteNumber',
  acre = 'acre',
  acre1000 = 'acre1000',
  annualNumberOfVisitsMillion = 'annualNumberOfVisitsMillion',
  cubicMeterPerHa = 'cubicMeterPerHa',
  facilityLengthIn1000Km = 'facilityLengthIn1000Km',
  fte1000 = 'fte1000',
  ha = 'ha',
  haMillion = 'haMillion',
  haThousand = 'haThousand',
  haThousandPerYear = 'haThousandPerYear',
  kmSq = 'kmSq',
  mileSq = 'mileSq',
  millionCubicMeter = 'millionCubicMeter',
  millionNationalCurrency = 'millionNationalCurrency',
  millionsCubicMeterOverBark = 'millionsCubicMeterOverBark',
  millionTonnes = 'millionTonnes',
  numberOfStudents = 'numberOfStudents',
  thousandCubicMeter = 'thousandCubicMeter',
  thousandCubicMeterOverBark = 'thousandCubicMeterOverBark',
  thousandCubicMeterRWE = 'thousandCubicMeterRWE',
  thousandPersons = 'thousandPersons',
  tonnesPerHa = 'tonnesPerHa',
}
