openapi: 3.0.0
paths:
  /cycle-data/descriptions:
    get:
      tags:
        - Data
      summary: Get Descriptions by cycle and country
      parameters:
        - $ref: '#/components/parameters/assessmentName'
        - $ref: '#/components/parameters/countryIso'
        - $ref: '#/components/parameters/cycleName'
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescriptionCountryValues'
              example:
                FIN:
                  carbonStock:
                    dataSources:
                      text: '<p>HTML-formatted content</p>'
                      dataSources:
                        - type: nationalForestInventory
                          uuid: a1b2c3d4-e5f6-7a89-b0c1-d2e3f4a5b6c7
                          year: '2019-2022'
                          comments: ''
                          reference: '<p>Reference text</p>'
                          variables:
                            - carbon_forest_above_ground
                            - carbon_forest_below_ground
                    generalComments:
                      text: '<p>HTML-formatted content</p>'
                  disturbances:
                    generalComments:
                      text: '<p>HTML-formatted content</p>'
                  extentOfForest:
                    generalComments:
                      text: '<p>HTML-formatted content</p>'
                  forestPolicy:
                    dataSources:
                      text: '<p>HTML-formatted content</p>'
                    generalComments:
                      text: '<p>HTML-formatted content</p>'
        '401':
          description: Unauthorized access.
