openapi: 3.0.0
paths:
  /cycle-data/original-data-points/original-data-point:
    get:
      tags:
        - Cycle data
      summary: Get National Data Point
      parameters:
        - $ref: '#/components/parameters/assessmentName'
        - $ref: '#/components/parameters/countryIso'
        - $ref: '#/components/parameters/cycleName'
        - in: query
          name: year
          description: Year of the National Data Point. For example, "1990".
          required: true
          schema:
            type: string
            example: "1990"
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                description: The resulting table data.
                $ref: '#/components/schemas/NationalDataPoint'
              example:
                id: 123
                countryIso: ITA
                year: 2015
                dataSources:
                  - uuid: "a1x2c3d4-e7f6-9a69-m0d1-f6i6f8d2w6c7"
                    reference: |
                      Example Reference Title, 2021.
                      Organization Name. Example Publisher.
                      http://example.com/resource
                    type:
                      - nationalForestInventory
                    comments: "Example comment about data source"
                comments:
                  extentOfForest: "<div>Extent of forest HTML-formatted comments</div>"
                  forestCharacteristics: "<div>Forest characteristics HTML-formatted comments</div>"
                nationalClasses:
                  - area: 1813.24
                    name: "Other Wooded Land"
                    uuid: "a1b2c3d4-e5f6-7a89-b0c1-d2e3f4a5b6c7"
                    definition: "Example definition text."
                    forestPercent: 0
                    forestNaturalPercent: null
                    otherWoodedLandPercent: 100
                    forestPlantationPercent: null
                    otherPlantedForestPercent: null
                    forestPlantationIntroducedPercent: null
                  - area: 9297.08
                    name: "Forest"
                    uuid: "abcdef12-3456-7890-abcd-ef1234567890"
                    definition: "Example definition text."
                    forestPercent: 100
                    forestNaturalPercent: 93.12
                    otherWoodedLandPercent: 0
                    forestPlantationPercent: 1.36
                    otherPlantedForestPercent: 5.52
                    forestPlantationIntroducedPercent: 73.77
                values:
                  total: "9297.08"
                  forestArea: "9297.08"
                  plantedForest: "639.639104"
                  primaryForest: null
                  otherWoodedLand: "1813.24"
                  totalForestArea: "9297.08"
                  naturalForestArea: "8657.440896"
                  plantationForestArea: "126.440288"
                  primaryForestPercent: null
                  otherPlantedForestArea: "513.198816"
                  plantationForestIntroducedArea: "93.2750004576"
        '401':
          description: Unauthorized access.
