// @ts-nocheck

export const carbonStock = {
  sectionName: 'carbonStock',
  sectionAnchor: '1.4a',
  tableSections: [
    {
      tableSpecs: [
        {
          name: 'table_1_4a',
          rows: [
            {
              idx: 'header_0',
              cols: [
                {
                  idx: 0,
                  colSpan: 1,
                  rowSpan: 3,
                  labelKey: 'panEuropean.carbonStock.categoryYear',
                  className: 'fra-table__header-cell-left',
                  type: 'header',
                },
                {
                  idx: 1,
                  colSpan: 2,
                  rowSpan: 1,
                  labelKey: 'panEuropean.carbonStock.carbonInAboveGroundAndBelowGroundLivingBiomass',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 2,
                  colSpan: 2,
                  rowSpan: 1,
                  labelKey: 'panEuropean.carbonStock.carbonInDeadwoodAndLitter',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 3,
                  colSpan: 1,
                  rowSpan: 2,
                  labelKey: 'panEuropean.carbonStock.soil_carbon',
                  className: 'fra-table__header-cell-left',
                  type: 'header',
                },
              ],
              type: 'header',
            },
            {
              idx: 'header_1',
              cols: [
                {
                  idx: 0,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.carbonStock.aboveGround',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 1,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.carbonStock.belowGround',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 2,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.carbonStock.deadwoodCarbon',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 3,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.carbonStock.litterCarbon',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
              ],
              type: 'header',
            },
            {
              idx: 'header_2',
              cols: [
                {
                  idx: 0,
                  colSpan: 5,
                  rowSpan: 1,
                  labelKey: 'panEuropean.carbonStock.millionMetricTonnes',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
              ],
              type: 'header',
            },
            {
              idx: 0,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStock.forest',
                  labelParams: { year: 2025 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              migration: {
                cycles: ['2025'],
              },
              labelKey: 'panEuropean.carbonStock.forest',
              labelParams: { year: 2025 },
              variableExport: 'forest_2025',
            },
            {
              idx: 1,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStock.forest',
                  labelParams: { year: 2020 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStock.forest',
              labelParams: { year: 2020 },
              variableExport: 'forest_2020',
            },
            {
              idx: 2,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStock.forest',
                  labelParams: { year: 2015 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStock.forest',
              labelParams: { year: 2015 },
              variableExport: 'forest_2015',
            },
            {
              idx: 3,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStock.forest',
                  labelParams: { year: 2010 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStock.forest',
              labelParams: { year: 2010 },
              variableExport: 'forest_2010',
            },
            {
              idx: 4,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStock.forest',
                  labelParams: { year: 2005 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStock.forest',
              labelParams: { year: 2005 },
              variableExport: 'forest_2005',
            },
            {
              idx: 5,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStock.forest',
                  labelParams: { year: 2000 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStock.forest',
              labelParams: { year: 2000 },
              variableExport: 'forest_2000',
            },
            {
              idx: 6,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStock.forest',
                  labelParams: { year: 1990 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStock.forest',
              labelParams: { year: 1990 },
              variableExport: 'forest_1990',
            },
            {
              idx: 7,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStock.other_wooded_land',
                  labelParams: { year: 2025 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              migration: {
                cycles: ['2025'],
              },
              labelKey: 'panEuropean.carbonStock.other_wooded_land',
              labelParams: { year: 2025 },
              variableExport: 'other_wooded_land_2025',
            },
            {
              idx: 8,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStock.other_wooded_land',
                  labelParams: { year: 2020 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStock.other_wooded_land',
              labelParams: { year: 2020 },
              variableExport: 'other_wooded_land_2020',
            },
            {
              idx: 9,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStock.other_wooded_land',
                  labelParams: { year: 2015 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStock.other_wooded_land',
              labelParams: { year: 2015 },
              variableExport: 'other_wooded_land_2015',
            },
            {
              idx: 10,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStock.other_wooded_land',
                  labelParams: { year: 2010 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStock.other_wooded_land',
              labelParams: { year: 2010 },
              variableExport: 'other_wooded_land_2010',
            },
            {
              idx: 11,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStock.other_wooded_land',
                  labelParams: { year: 2005 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStock.other_wooded_land',
              labelParams: { year: 2005 },
              variableExport: 'other_wooded_land_2005',
            },
            {
              idx: 12,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStock.other_wooded_land',
                  labelParams: { year: 2000 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStock.other_wooded_land',
              labelParams: { year: 2000 },
              variableExport: 'other_wooded_land_2000',
            },
            {
              idx: 13,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStock.other_wooded_land',
                  labelParams: { year: 1990 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStock.other_wooded_land',
              labelParams: { year: 1990 },
              variableExport: 'other_wooded_land_1990',
            },
            {
              idx: 14,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStock.total_forest_and_other_wooded_land',
                  labelParams: { year: 2025 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              migration: {
                cycles: ['2025'],
                validateFns: [
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2025['above_ground'],
                  [table_1_4a.other_wooded_land_2025['above_ground'],table_1_4a.forest_2025['above_ground']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2025['below_ground'],
                  [table_1_4a.other_wooded_land_2025['below_ground'],table_1_4a.forest_2025['below_ground']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2025['deadwood'],
                  [table_1_4a.other_wooded_land_2025['deadwood'],table_1_4a.forest_2025['deadwood']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2025['litter'],
                  [table_1_4a.other_wooded_land_2025['litter'],table_1_4a.forest_2025['litter']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2025['soil_carbon'],
                  [table_1_4a.other_wooded_land_2025['soil_carbon'],table_1_4a.forest_2025['soil_carbon']])`,
                ],
              },
              labelKey: 'panEuropean.carbonStock.total_forest_and_other_wooded_land',
              labelParams: { year: 2025 },
              variableExport: 'total_forest_and_other_wooded_land_2025',
            },
            {
              idx: 15,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStock.total_forest_and_other_wooded_land',
                  labelParams: { year: 2020 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              migration: {
                validateFns: [
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2020['above_ground'],
                  [table_1_4a.other_wooded_land_2020['above_ground'],table_1_4a.forest_2020['above_ground']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2020['below_ground'],
                  [table_1_4a.other_wooded_land_2020['below_ground'],table_1_4a.forest_2020['below_ground']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2020['deadwood'],
                  [table_1_4a.other_wooded_land_2020['deadwood'],table_1_4a.forest_2020['deadwood']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2020['litter'],
                  [table_1_4a.other_wooded_land_2020['litter'],table_1_4a.forest_2020['litter']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2020['soil_carbon'],
                  [table_1_4a.other_wooded_land_2020['soil_carbon'],table_1_4a.forest_2020['soil_carbon']])`,
                ],
              },
              labelKey: 'panEuropean.carbonStock.total_forest_and_other_wooded_land',
              labelParams: { year: 2020 },
              variableExport: 'total_forest_and_other_wooded_land_2020',
            },
            {
              idx: 16,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStock.total_forest_and_other_wooded_land',
                  labelParams: { year: 2015 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              migration: {
                validateFns: [
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2015['above_ground'],
                  [table_1_4a.other_wooded_land_2015['above_ground'],table_1_4a.forest_2015['above_ground']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2015['below_ground'],
                  [table_1_4a.other_wooded_land_2015['below_ground'],table_1_4a.forest_2015['below_ground']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2015['deadwood'],
                  [table_1_4a.other_wooded_land_2015['deadwood'],table_1_4a.forest_2015['deadwood']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2015['litter'],
                  [table_1_4a.other_wooded_land_2015['litter'],table_1_4a.forest_2015['litter']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2015['soil_carbon'],
                  [table_1_4a.other_wooded_land_2015['soil_carbon'],table_1_4a.forest_2015['soil_carbon']])`,
                ],
              },
              labelKey: 'panEuropean.carbonStock.total_forest_and_other_wooded_land',
              labelParams: { year: 2015 },
              variableExport: 'total_forest_and_other_wooded_land_2015',
            },
            {
              idx: 17,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStock.total_forest_and_other_wooded_land',
                  labelParams: { year: 2010 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              migration: {
                validateFns: [
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2010['above_ground'],
                  [table_1_4a.other_wooded_land_2010['above_ground'],table_1_4a.forest_2010['above_ground']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2010['below_ground'],
                  [table_1_4a.other_wooded_land_2010['below_ground'],table_1_4a.forest_2010['below_ground']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2010['deadwood'],
                  [table_1_4a.other_wooded_land_2010['deadwood'],table_1_4a.forest_2010['deadwood']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2010['litter'],
                  [table_1_4a.other_wooded_land_2010['litter'],table_1_4a.forest_2010['litter']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2010['soil_carbon'],
                  [table_1_4a.other_wooded_land_2010['soil_carbon'],table_1_4a.forest_2010['soil_carbon']])`,
                ],
              },
              labelKey: 'panEuropean.carbonStock.total_forest_and_other_wooded_land',
              labelParams: { year: 2010 },
              variableExport: 'total_forest_and_other_wooded_land_2010',
            },
            {
              idx: 18,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStock.total_forest_and_other_wooded_land',
                  labelParams: { year: 2005 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              migration: {
                validateFns: [
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2005['above_ground'],
                  [table_1_4a.other_wooded_land_2005['above_ground'],table_1_4a.forest_2005['above_ground']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2005['below_ground'],
                  [table_1_4a.other_wooded_land_2005['below_ground'],table_1_4a.forest_2005['below_ground']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2005['deadwood'],
                  [table_1_4a.other_wooded_land_2005['deadwood'],table_1_4a.forest_2005['deadwood']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2005['litter'],
                  [table_1_4a.other_wooded_land_2005['litter'],table_1_4a.forest_2005['litter']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2005['soil_carbon'],
                  [table_1_4a.other_wooded_land_2005['soil_carbon'],table_1_4a.forest_2005['soil_carbon']])`,
                ],
              },
              labelKey: 'panEuropean.carbonStock.total_forest_and_other_wooded_land',
              labelParams: { year: 2005 },
              variableExport: 'total_forest_and_other_wooded_land_2005',
            },
            {
              idx: 19,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStock.total_forest_and_other_wooded_land',
                  labelParams: { year: 2000 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              migration: {
                validateFns: [
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2000['above_ground'],
                  [table_1_4a.other_wooded_land_2000['above_ground'],table_1_4a.forest_2000['above_ground']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2000['below_ground'],
                  [table_1_4a.other_wooded_land_2000['below_ground'],table_1_4a.forest_2000['below_ground']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2000['deadwood'],
                  [table_1_4a.other_wooded_land_2000['deadwood'],table_1_4a.forest_2000['deadwood']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2000['litter'],
                  [table_1_4a.other_wooded_land_2000['litter'],table_1_4a.forest_2000['litter']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_2000['soil_carbon'],
                  [table_1_4a.other_wooded_land_2000['soil_carbon'],table_1_4a.forest_2000['soil_carbon']])`,
                ],
              },
              labelKey: 'panEuropean.carbonStock.total_forest_and_other_wooded_land',
              labelParams: { year: 2000 },
              variableExport: 'total_forest_and_other_wooded_land_2000',
            },
            {
              idx: 20,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStock.total_forest_and_other_wooded_land',
                  labelParams: { year: 1990 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              migration: {
                validateFns: [
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_1990['above_ground'],
                  [table_1_4a.other_wooded_land_1990['above_ground'],table_1_4a.forest_1990['above_ground']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_1990['below_ground'],
                  [table_1_4a.other_wooded_land_1990['below_ground'],table_1_4a.forest_1990['below_ground']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_1990['deadwood'],
                  [table_1_4a.other_wooded_land_1990['deadwood'],table_1_4a.forest_1990['deadwood']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_1990['litter'],
                  [table_1_4a.other_wooded_land_1990['litter'],table_1_4a.forest_1990['litter']])`,
                  `validatorEqualToSum(table_1_4a.total_forest_and_other_wooded_land_1990['soil_carbon'],
                  [table_1_4a.other_wooded_land_1990['soil_carbon'],table_1_4a.forest_1990['soil_carbon']])`,
                ],
              },
              labelKey: 'panEuropean.carbonStock.total_forest_and_other_wooded_land',
              labelParams: { year: 1990 },
              variableExport: 'total_forest_and_other_wooded_land_1990',
            },
          ],
          tableDataRequired: [],
          print: { colBreakPoints: [], pageBreakAfter: false },
          dataExport: true,
          columnsExportAlways: [],
          unit: 'millionTonnes',
          columnsExport: ['above_ground', 'below_ground', 'deadwood', 'litter', 'soil_carbon'],
        },
      ],
    },
    {
      titleKey: 'panEuropean.countryComments.carbonStockInHarvestedWoodProductsHWP',
      tableSpecs: [
        {
          name: 'table_1_4b',
          rows: [
            {
              idx: 'header_0',
              cols: [
                {
                  idx: 0,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.categoryYear',
                  className: 'fra-table__header-cell-left',
                  type: 'header',
                },
                {
                  idx: 1,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey:
                    'panEuropean.carbonStockInHarvestedWoodProductsHWP.totalCarbonStockInHWPMillionMetricTonnes',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
              ],
              type: 'header',
            },
            {
              idx: 0,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
                  labelParams: { year: 2025 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
              ],
              migration: {
                cycles: ['2025'],
              },
              labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
              labelParams: { year: 2025 },
              variableExport: 'harvested_wood_products_2025',
            },
            {
              idx: 1,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
                  labelParams: { year: 2020 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
              ],
              migration: {
                cycles: ['2025'],
              },
              labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
              labelParams: { year: 2020 },
              variableExport: 'harvested_wood_products_2020',
            },
            {
              idx: 2,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
                  labelParams: { year: 2015 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
              labelParams: { year: 2015 },
              variableExport: 'harvested_wood_products_2015',
            },
            {
              idx: 3,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
                  labelParams: { year: 2010 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
              labelParams: { year: 2010 },
              variableExport: 'harvested_wood_products_2010',
            },
            {
              idx: 4,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
                  labelParams: { year: 2005 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
              labelParams: { year: 2005 },
              variableExport: 'harvested_wood_products_2005',
            },
            {
              idx: 5,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
                  labelParams: { year: 2000 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
              labelParams: { year: 2000 },
              variableExport: 'harvested_wood_products_2000',
            },
            {
              idx: 6,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
                  labelParams: { year: 1990 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
              labelParams: { year: 1990 },
              variableExport: 'harvested_wood_products_1990',
            },
          ],
          tableDataRequired: [],
          print: { colBreakPoints: [], pageBreakAfter: false },
          dataExport: true,
          columnsExportAlways: [],
          unit: 'millionTonnes',
          columnsExport: ['total_carbon_stock_in_hwp'],
          migration: {
            cycles: ['2025'],
          },
        },
      ],
    },
    {
      titleKey: 'panEuropean.countryComments.countryComments',
      tableSpecs: [
        {
          name: 'country_comments_1_4_1',
          rows: [
            {
              idx: 'header_0',
              cols: [
                {
                  idx: 0,
                  colSpan: 3,
                  rowSpan: 1,
                  labelKey: 'panEuropean.countryComments.theYearAndDataReportedFor2025',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
              ],
              type: 'header',
            },
            {
              idx: 0,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  rowSpan: 3,
                  labelKey: 'panEuropean.countryComments.howDidYouGenerateValuesFor2025',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: -1,
                  colSpan: 1,
                  labelKey: 'panEuropean.countryComments.theRecentAvailableYear',
                  className: 'fra-table__header-cell',
                  type: 'placeholder',
                },
                { idx: 0, type: 'textarea' },
              ],
            },
            {
              idx: 1,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  labelKey: 'panEuropean.countryComments.extrapolation',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'textarea' },
              ],
            },
            {
              idx: 2,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  labelKey: 'panEuropean.countryComments.assessmentBasedOnEvidence',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'textarea' },
              ],
            },
          ],
          tableDataRequired: [],
          print: { colBreakPoints: [], pageBreakAfter: false },
          dataExport: true,
          columnsExportAlways: [],
          columnsExport: [],
          migration: {
            cycles: ['2025'],
            columnNames: { '2025': ['theYearAndDataReportedFor2025'] },
          },
        },
      ],
    },
    {
      tableSpecs: [
        {
          name: 'country_comments_1_4_2',
          rows: [
            {
              idx: 'header_0',
              cols: [
                {
                  idx: 0,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.countryComments.category',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 1,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.countryComments.commentsRelatedToDataDefinitionsConversionFactorsUsed',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 2,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.countryComments.commentsOnTrend',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
              ],
              type: 'header',
            },
            {
              idx: 0,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  labelKey: 'panEuropean.countryComments.carbonStockInAboveGroundLivingBiomass',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
              ],
            },
            {
              idx: 1,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  labelKey: 'panEuropean.countryComments.carbonStockInAboveGroundLivingBiomass',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
              ],
            },
            {
              idx: 2,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  labelKey: 'panEuropean.countryComments.carbonStockInDeadwood',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
              ],
            },
            {
              idx: 3,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  labelKey: 'panEuropean.countryComments.carbonStockInLitter',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
              ],
            },
            {
              idx: 4,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  labelKey: 'panEuropean.countryComments.carbonStockInSoil',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
              ],
            },
            {
              idx: 5,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  labelKey: 'panEuropean.countryComments.biomassCarbonConversionFactorUsed',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
              ],
            },
          ],
          tableDataRequired: [],
          print: { colBreakPoints: [], pageBreakAfter: false },
          dataExport: true,
          columnsExportAlways: [],
          columnsExport: [],
          migration: {
            cycles: ['2025'],
            columnNames: {
              '2025': ['category', 'commentsRelatedToDataDefinitionsConversionFactorsUsed', 'commentsOnTrend'],
            },
          },
        },
      ],
    },
  ],
  showTitle: true,
  descriptions: {
    analysisAndProcessing: true,
    comments: true,
    introductoryText: false,
    nationalData: true,
  },
  dataExport: {
    included: true,
  },
  migration: {
    anchors: {
      '2020': '1.4a',
      '2025': '1.4',
    },
  },
}
export const carbonStockInHarvestedWoodProductsHWP = {
  sectionName: 'carbonStockInHarvestedWoodProductsHWP',
  sectionAnchor: '1.4b',
  tableSections: [
    {
      tableSpecs: [
        {
          name: 'table_1_4b',
          rows: [
            {
              idx: 'header_0',
              cols: [
                {
                  idx: 0,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.categoryYear',
                  className: 'fra-table__header-cell-left',
                  type: 'header',
                },
                {
                  idx: 1,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey:
                    'panEuropean.carbonStockInHarvestedWoodProductsHWP.totalCarbonStockInHWPMillionMetricTonnes',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
              ],
              type: 'header',
            },
            {
              idx: 0,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
                  labelParams: { year: 2025 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
              ],
              migration: {
                cycles: ['2025'],
              },
              labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
              labelParams: { year: 2025 },
              variableExport: 'harvested_wood_products_2025',
            },
            {
              idx: 1,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
                  labelParams: { year: 2020 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
              ],
              migration: {
                cycles: ['2025'],
              },
              labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
              labelParams: { year: 2020 },
              variableExport: 'harvested_wood_products_2020',
            },
            {
              idx: 2,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
                  labelParams: { year: 2015 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
              labelParams: { year: 2015 },
              variableExport: 'harvested_wood_products_2015',
            },
            {
              idx: 3,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
                  labelParams: { year: 2010 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
              labelParams: { year: 2010 },
              variableExport: 'harvested_wood_products_2010',
            },
            {
              idx: 4,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
                  labelParams: { year: 2005 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWP.harvested_wood_products',
              labelParams: { year: 2005 },
              variableExport: 'harvested_wood_products_2005',
            },
            {
              idx: 5,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWPharvested_wood_products',
                  labelParams: { year: 2000 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWPharvested_wood_products',
              labelParams: { year: 2000 },
              variableExport: 'harvested_wood_products_2000',
            },
            {
              idx: 6,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWPharvested_wood_products',
                  labelParams: { year: 1990 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
              ],
              labelKey: 'panEuropean.carbonStockInHarvestedWoodProductsHWPharvested_wood_products',
              labelParams: { year: 1990 },
              variableExport: 'harvested_wood_products_1990',
            },
          ],
          tableDataRequired: [],
          print: { colBreakPoints: [], pageBreakAfter: false },
          dataExport: true,
          columnsExportAlways: [],
          unit: 'millionTonnes',
          columnsExport: ['total_carbon_stock_in_hwp'],
        },
      ],
    },
  ],
  showTitle: true,
  descriptions: {
    analysisAndProcessing: true,
    comments: true,
    introductoryText: false,
    nationalData: true,
  },
  dataExport: {
    included: true,
  },
  migration: {
    cycles: ['2020'],
  },
}
