// @ts-nocheck

export const employmentByGenderAndAge = {
  sectionName: 'employmentByGenderAndAge',
  sectionAnchor: '6.5a',
  tableSections: [
    {
      tableSpecs: [
        {
          name: 'table_6_5a',
          rows: [
            {
              idx: 'header_0',
              cols: [
                {
                  idx: 0,
                  colSpan: 1,
                  rowSpan: 3,
                  labelKey: 'panEuropean.employmentByGenderAndAge.categoryYear',
                  className: 'fra-table__header-cell-left',
                  type: 'header',
                },
                {
                  idx: 1,
                  colSpan: 5,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.employmentByGenderAge1000p',
                  className: 'fra-table__header-cell-left',
                  type: 'header',
                  migration: {
                    cycles: ['2025'],
                  },
                },
                {
                  idx: 2,
                  colSpan: 1,
                  rowSpan: 2,
                  labelKey: 'panEuropean.employmentByGenderAndAge.total',
                  className: 'fra-table__header-cell',
                  type: 'header',
                  migration: {
                    cycles: ['2020'],
                  },
                },
                {
                  idx: 3,
                  colSpan: 2,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.gender',
                  className: 'fra-table__header-cell',
                  type: 'header',
                  migration: {
                    cycles: ['2020'],
                  },
                },
                {
                  idx: 4,
                  colSpan: 2,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.ageGroup',
                  className: 'fra-table__header-cell',
                  type: 'header',
                  migration: {
                    cycles: ['2020'],
                  },
                },
              ],
              type: 'header',
            },
            {
              idx: 'header_1',
              cols: [
                {
                  idx: 0,
                  colSpan: 1,
                  rowSpan: 2,
                  labelKey: 'panEuropean.employmentByGenderAndAge.total',
                  className: 'fra-table__header-cell',
                  type: 'header',
                  migration: {
                    cycles: ['2025'],
                  },
                },
                {
                  idx: 1,
                  colSpan: 2,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.gender',
                  className: 'fra-table__header-cell',
                  type: 'header',
                  migration: {
                    cycles: ['2025'],
                  },
                },
                {
                  idx: 2,
                  colSpan: 2,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.ageGroup',
                  className: 'fra-table__header-cell',
                  type: 'header',
                  migration: {
                    cycles: ['2025'],
                  },
                },
                {
                  idx: 3,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.male',
                  className: 'fra-table__header-cell',
                  type: 'header',
                  migration: {
                    cycles: ['2020'],
                  },
                },
                {
                  idx: 4,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.female',
                  className: 'fra-table__header-cell',
                  type: 'header',
                  migration: {
                    cycles: ['2020'],
                  },
                },
                {
                  idx: 5,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge._15_49',
                  className: 'fra-table__header-cell',
                  type: 'header',
                  migration: {
                    cycles: ['2020'],
                  },
                },
                {
                  idx: 6,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge._50_',
                  className: 'fra-table__header-cell',
                  type: 'header',
                  migration: {
                    cycles: ['2020'],
                  },
                },
              ],
              type: 'header',
            },
            {
              idx: 'header_2',
              cols: [
                {
                  idx: 0,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.male',
                  className: 'fra-table__header-cell',
                  type: 'header',
                  migration: {
                    cycles: ['2025'],
                  },
                },
                {
                  idx: 1,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.female',
                  className: 'fra-table__header-cell',
                  type: 'header',
                  migration: {
                    cycles: ['2025'],
                  },
                },
                {
                  idx: 2,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge._15_49',
                  className: 'fra-table__header-cell',
                  type: 'header',
                  migration: {
                    cycles: ['2025'],
                  },
                },
                {
                  idx: 3,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge._50_',
                  className: 'fra-table__header-cell',
                  type: 'header',
                  migration: {
                    cycles: ['2025'],
                  },
                },
                {
                  idx: 4,
                  colSpan: 5,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge._1000Persons',
                  className: 'fra-table__header-cell',
                  type: 'header',
                  migration: {
                    cycles: ['2020'],
                  },
                },
              ],
              type: 'header',
            },
            {
              idx: 0,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.forestry',
                  labelParams: { year: 2020 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              migration: {
                cycles: ['2025'],
              },
              labelKey: 'panEuropean.employmentByGenderAndAge.forestry',
              labelParams: { year: 2020 },
              variableExport: 'forestry_2020',
            },
            {
              idx: 1,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.forestry',
                  labelParams: { year: 2015 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByGenderAndAge.forestry',
              labelParams: { year: 2015 },
              variableExport: 'forestry_2015',
            },
            {
              idx: 2,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.forestry',
                  labelParams: { year: 2010 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByGenderAndAge.forestry',
              labelParams: { year: 2010 },
              variableExport: 'forestry_2010',
            },
            {
              idx: 3,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.forestry',
                  labelParams: { year: 2005 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByGenderAndAge.forestry',
              labelParams: { year: 2005 },
              variableExport: 'forestry_2005',
            },
            {
              idx: 4,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.forestry',
                  labelParams: { year: 2000 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByGenderAndAge.forestry',
              labelParams: { year: 2000 },
              variableExport: 'forestry_2000',
            },
            {
              idx: 5,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.forestry',
                  labelParams: { year: 1990 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByGenderAndAge.forestry',
              labelParams: { year: 1990 },
              variableExport: 'forestry_1990',
            },
            {
              idx: 6,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_wood_and_articles_in_wood',
                  labelParams: { year: 2020 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              migration: {
                cycles: ['2025'],
              },
              labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_wood_and_articles_in_wood',
              labelParams: { year: 2020 },
              variableExport: 'manufacture_of_wood_and_articles_in_wood_2020',
            },
            {
              idx: 7,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_wood_and_articles_in_wood',
                  labelParams: { year: 2015 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_wood_and_articles_in_wood',
              labelParams: { year: 2015 },
              variableExport: 'manufacture_of_wood_and_articles_in_wood_2015',
            },
            {
              idx: 8,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_wood_and_articles_in_wood',
                  labelParams: { year: 2010 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_wood_and_articles_in_wood',
              labelParams: { year: 2010 },
              variableExport: 'manufacture_of_wood_and_articles_in_wood_2010',
            },
            {
              idx: 9,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_wood_and_articles_in_wood',
                  labelParams: { year: 2005 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_wood_and_articles_in_wood',
              labelParams: { year: 2005 },
              variableExport: 'manufacture_of_wood_and_articles_in_wood_2005',
            },
            {
              idx: 10,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_wood_and_articles_in_wood',
                  labelParams: { year: 2000 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_wood_and_articles_in_wood',
              labelParams: { year: 2000 },
              variableExport: 'manufacture_of_wood_and_articles_in_wood_2000',
            },
            {
              idx: 11,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_wood_and_articles_in_wood',
                  labelParams: { year: 1990 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_wood_and_articles_in_wood',
              labelParams: { year: 1990 },
              variableExport: 'manufacture_of_wood_and_articles_in_wood_1990',
            },
            {
              idx: 12,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_paper_and_paper_products',
                  labelParams: { year: 2020 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_paper_and_paper_products',
              labelParams: { year: 2020 },
              variableExport: 'manufacture_of_paper_and_paper_products_2020',
            },
            {
              idx: 13,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_paper_and_paper_products',
                  labelParams: { year: 2015 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_paper_and_paper_products',
              labelParams: { year: 2015 },
              variableExport: 'manufacture_of_paper_and_paper_products_2015',
            },
            {
              idx: 14,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_paper_and_paper_products',
                  labelParams: { year: 2010 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_paper_and_paper_products',
              labelParams: { year: 2010 },
              variableExport: 'manufacture_of_paper_and_paper_products_2010',
            },
            {
              idx: 15,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_paper_and_paper_products',
                  labelParams: { year: 2005 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_paper_and_paper_products',
              labelParams: { year: 2005 },
              variableExport: 'manufacture_of_paper_and_paper_products_2005',
            },
            {
              idx: 16,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_paper_and_paper_products',
                  labelParams: { year: 2000 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_paper_and_paper_products',
              labelParams: { year: 2000 },
              variableExport: 'manufacture_of_paper_and_paper_products_2000',
            },
            {
              idx: 17,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_paper_and_paper_products',
                  labelParams: { year: 1990 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByGenderAndAge.manufacture_of_paper_and_paper_products',
              labelParams: { year: 1990 },
              variableExport: 'manufacture_of_paper_and_paper_products_1990',
            },
          ],
          tableDataRequired: [],
          print: { colBreakPoints: [], pageBreakAfter: false },
          dataExport: true,
          columnsExportAlways: [],
          unit: 'thousandPersons',
          columnsExport: ['total', 'gender_male', 'gender_female', 'age_group_15_49', 'age_group_50_plus'],
        },
      ],
    },
    {
      titleKey: 'panEuropean.countryComments.EmploymentByEducationAndJobCharacteristics',

      tableSpecs: [
        {
          name: 'table_6_5b',
          rows: [
            {
              idx: 'header_0',
              cols: [
                {
                  idx: 0,
                  colSpan: 1,
                  rowSpan: 3,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.categoryYear',
                  className: 'fra-table__header-cell-left',
                  type: 'header',
                },
                {
                  idx: 1,
                  colSpan: 3,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.education',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 2,
                  colSpan: 2,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.jobCharacteristics',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
              ],
              type: 'header',
            },
            {
              idx: 'header_1',
              cols: [
                {
                  idx: 0,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics._0_2',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 1,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics._3_4',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 2,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics._5_6',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 3,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.employeesJobCharacteristics',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 4,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.selfEmployed',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
              ],
              type: 'header',
            },
            {
              idx: 'header_2',
              cols: [
                {
                  idx: 0,
                  colSpan: 5,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics._1000Persons',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
              ],
              type: 'header',
            },
            {
              idx: 0,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
                  labelParams: { year: 2020 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              migration: {
                cycles: ['2025'],
              },
              labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
              labelParams: { year: 2020 },
              variableExport: 'forestry_2020',
            },
            {
              idx: 1,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
                  labelParams: { year: 2015 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
              labelParams: { year: 2015 },
              variableExport: 'forestry_2015',
            },
            {
              idx: 2,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
                  labelParams: { year: 2010 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
              labelParams: { year: 2010 },
              variableExport: 'forestry_2010',
            },
            {
              idx: 3,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
                  labelParams: { year: 2005 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
              labelParams: { year: 2005 },
              variableExport: 'forestry_2005',
            },
            {
              idx: 4,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
                  labelParams: { year: 2000 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
              labelParams: { year: 2000 },
              variableExport: 'forestry_2000',
            },
            {
              idx: 5,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
                  labelParams: { year: 1990 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
              labelParams: { year: 1990 },
              variableExport: 'forestry_1990',
            },
            {
              idx: 6,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
                  labelParams: { year: 2020 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              migration: {
                cycles: ['2025'],
              },
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
              labelParams: { year: 2020 },
              variableExport: 'manufacture_of_wood_and_articles_in_wood_2020',
            },
            {
              idx: 7,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
                  labelParams: { year: 2015 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
              labelParams: { year: 2015 },
              variableExport: 'manufacture_of_wood_and_articles_in_wood_2015',
            },
            {
              idx: 8,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
                  labelParams: { year: 2010 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
              labelParams: { year: 2010 },
              variableExport: 'manufacture_of_wood_and_articles_in_wood_2010',
            },
            {
              idx: 9,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
                  labelParams: { year: 2005 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
              labelParams: { year: 2005 },
              variableExport: 'manufacture_of_wood_and_articles_in_wood_2005',
            },
            {
              idx: 10,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
                  labelParams: { year: 2000 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
              labelParams: { year: 2000 },
              variableExport: 'manufacture_of_wood_and_articles_in_wood_2000',
            },
            {
              idx: 11,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
                  labelParams: { year: 1990 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
              labelParams: { year: 1990 },
              variableExport: 'manufacture_of_wood_and_articles_in_wood_1990',
            },
            {
              idx: 12,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
                  labelParams: { year: 2020 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              migration: {
                cycles: ['2025'],
              },
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
              labelParams: { year: 2020 },
              variableExport: 'manufacture_of_paper_and_paper_products_2020',
            },
            {
              idx: 13,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
                  labelParams: { year: 2015 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
              labelParams: { year: 2015 },
              variableExport: 'manufacture_of_paper_and_paper_products_2015',
            },
            {
              idx: 14,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
                  labelParams: { year: 2010 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
              labelParams: { year: 2010 },
              variableExport: 'manufacture_of_paper_and_paper_products_2010',
            },
            {
              idx: 15,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
                  labelParams: { year: 2005 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
              labelParams: { year: 2005 },
              variableExport: 'manufacture_of_paper_and_paper_products_2005',
            },
            {
              idx: 16,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
                  labelParams: { year: 2000 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
              labelParams: { year: 2000 },
              variableExport: 'manufacture_of_paper_and_paper_products_2000',
            },
            {
              idx: 17,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
                  labelParams: { year: 1990 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
              labelParams: { year: 1990 },
              variableExport: 'manufacture_of_paper_and_paper_products_1990',
            },
          ],
          tableDataRequired: [],
          print: { colBreakPoints: [], pageBreakAfter: false },
          dataExport: true,
          columnsExportAlways: [],
          unit: 'thousandPersons',
          columnsExport: ['education_0_2', 'education_3_4', 'education_5_6', 'employees', 'self_employed'],
          migration: {
            label: {
              '2025': {
                key: 'panEuropean.employmentByEducationAndJobCharacteristics.employmentByEducationAndJobCharacteristics',
              },
            },
            cycles: ['2025'],
          },
        },
      ],
    },
    {
      titleKey: 'panEuropean.countryComments.countryComments',
      tableSpecs: [
        {
          name: 'country_comments_6_5_1',
          rows: [
            {
              idx: 'header_0',
              cols: [
                {
                  idx: 0,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.countryComments.scopeOfEmploymentReportedIfNotFromLfs',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'text' },
              ],
              type: 'data',
            },
            {
              idx: 0,
              type: 'data',
              variableName: 'commentsOnEmploymentWhichIsNotCoveredByTheSourcesUsed',
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  labelKey: 'panEuropean.countryComments.commentsOnEmploymentWhichIsNotCoveredByTheSourcesUsed',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'textarea', colName: 'comment' },
              ],
            },
          ],
          tableDataRequired: [],
          print: { colBreakPoints: [], pageBreakAfter: false },
          dataExport: true,
          columnsExportAlways: [],
          columnsExport: [],
          migration: {
            cycles: ['2025'],
            columnNames: {
              '2025': ['comment'],
            },
          },
        },
      ],
    },
    {
      tableSpecs: [
        {
          name: 'country_comments_6_5_2',
          rows: [
            {
              idx: 'header_0',
              cols: [
                {
                  idx: 0,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.countryComments.category',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 1,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.countryComments.commentsRelatedToDataDefinitions',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 2,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.countryComments.commentsOnTrend',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
              ],
              type: 'header',
            },
            ...[
              'generalComments',
              'forestry',
              'manufactureOfWoodAndOfProductsOfWood',
              'manufactureOfPaperAndPaperProducts',
            ].map((variableName, idx) => ({
              idx,
              type: 'data',
              variableName,
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  labelKey: `panEuropean.countryComments.${variableName}`,
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'textarea', colName: 'comment' },
                { idx: 1, type: 'textarea', colName: 'comment_trends' },
              ],
            })),
          ],
          tableDataRequired: [],
          print: { colBreakPoints: [], pageBreakAfter: false },
          dataExport: true,
          columnsExportAlways: [],
          columnsExport: [],
          migration: {
            cycles: ['2025'],
            columnNames: { '2025': ['comment', 'comment_trends'] },
          },
        },
      ],
    },
  ],
  showTitle: true,
  descriptions: {
    analysisAndProcessing: true,
    comments: true,
    introductoryText: false,
    nationalData: true,
  },
  dataExport: {
    included: true,
  },
  migration: {
    anchors: {
      '2020': '6.5a',
      '2025': '6.5',
    },
    hidden: true,
  },
}
export const employmentByEducationAndJobCharacteristics = {
  sectionName: 'employmentByEducationAndJobCharacteristics',
  sectionAnchor: '6.5b',
  tableSections: [
    {
      tableSpecs: [
        {
          name: 'table_6_5b',
          rows: [
            {
              idx: 'header_0',
              cols: [
                {
                  idx: 0,
                  colSpan: 1,
                  rowSpan: 3,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.categoryYear',
                  className: 'fra-table__header-cell-left',
                  type: 'header',
                },
                {
                  idx: 1,
                  colSpan: 3,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.education',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 2,
                  colSpan: 2,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.jobCharacteristics',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
              ],
              type: 'header',
            },
            {
              idx: 'header_1',
              cols: [
                {
                  idx: 0,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics._0_2',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 1,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics._3_4',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 2,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics._5_6',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 3,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.employeesJobCharacteristics',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 4,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.selfEmployed',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
              ],
              type: 'header',
            },
            {
              idx: 'header_2',
              cols: [
                {
                  idx: 0,
                  colSpan: 5,
                  rowSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics._1000Persons',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
              ],
              type: 'header',
            },
            {
              idx: 0,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
                  labelParams: { year: 2020 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              migration: {
                cycles: ['2025'],
              },
              labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
              labelParams: { year: 2020 },
              variableExport: 'forestry_2020',
            },
            {
              idx: 1,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
                  labelParams: { year: 2015 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
              labelParams: { year: 2015 },
              variableExport: 'forestry_2015',
            },
            {
              idx: 2,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
                  labelParams: { year: 2010 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
              labelParams: { year: 2010 },
              variableExport: 'forestry_2010',
            },
            {
              idx: 3,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
                  labelParams: { year: 2005 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
              labelParams: { year: 2005 },
              variableExport: 'forestry_2005',
            },
            {
              idx: 4,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
                  labelParams: { year: 2000 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
              labelParams: { year: 2000 },
              variableExport: 'forestry_2000',
            },
            {
              idx: 5,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
                  labelParams: { year: 1990 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey: 'panEuropean.employmentByEducationAndJobCharacteristics.forestry',
              labelParams: { year: 1990 },
              variableExport: 'forestry_1990',
            },
            {
              idx: 6,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
                  labelParams: { year: 2020 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              migration: {
                cycles: ['2025'],
              },
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
              labelParams: { year: 2020 },
              variableExport: 'manufacture_of_wood_and_articles_in_wood_2020',
            },
            {
              idx: 7,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
                  labelParams: { year: 2015 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
              labelParams: { year: 2015 },
              variableExport: 'manufacture_of_wood_and_articles_in_wood_2015',
            },
            {
              idx: 8,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
                  labelParams: { year: 2010 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
              labelParams: { year: 2010 },
              variableExport: 'manufacture_of_wood_and_articles_in_wood_2010',
            },
            {
              idx: 9,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
                  labelParams: { year: 2005 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
              labelParams: { year: 2005 },
              variableExport: 'manufacture_of_wood_and_articles_in_wood_2005',
            },
            {
              idx: 10,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
                  labelParams: { year: 2000 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
              labelParams: { year: 2000 },
              variableExport: 'manufacture_of_wood_and_articles_in_wood_2000',
            },
            {
              idx: 11,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
                  labelParams: { year: 1990 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_wood_and_articles_in_wood',
              labelParams: { year: 1990 },
              variableExport: 'manufacture_of_wood_and_articles_in_wood_1990',
            },
            {
              idx: 12,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
                  labelParams: { year: 2020 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              migration: {
                cycles: ['2025'],
              },
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
              labelParams: { year: 2020 },
              variableExport: 'manufacture_of_paper_and_paper_products_2020',
            },
            {
              idx: 13,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
                  labelParams: { year: 2015 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
              labelParams: { year: 2015 },
              variableExport: 'manufacture_of_paper_and_paper_products_2015',
            },
            {
              idx: 14,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
                  labelParams: { year: 2010 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
              labelParams: { year: 2010 },
              variableExport: 'manufacture_of_paper_and_paper_products_2010',
            },
            {
              idx: 15,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
                  labelParams: { year: 2005 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
              labelParams: { year: 2005 },
              variableExport: 'manufacture_of_paper_and_paper_products_2005',
            },
            {
              idx: 16,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
                  labelParams: { year: 2000 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
              labelParams: { year: 2000 },
              variableExport: 'manufacture_of_paper_and_paper_products_2000',
            },
            {
              idx: 17,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey:
                    'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
                  labelParams: { year: 1990 },
                  className: 'fra-table__category-cell',
                },
                { idx: 0, type: 'decimal' },
                { idx: 1, type: 'decimal' },
                {
                  idx: 2,
                  type: 'decimal',
                },
                { idx: 3, type: 'decimal' },
                { idx: 4, type: 'decimal' },
              ],
              labelKey:
                'panEuropean.employmentByEducationAndJobCharacteristics.manufacture_of_paper_and_paper_products',
              labelParams: { year: 1990 },
              variableExport: 'manufacture_of_paper_and_paper_products_1990',
            },
          ],
          tableDataRequired: [],
          print: { colBreakPoints: [], pageBreakAfter: false },
          dataExport: true,
          columnsExportAlways: [],
          unit: 'thousandPersons',
          columnsExport: ['education_0_2', 'education_3_4', 'education_5_6', 'employees', 'self_employed'],
        },
      ],
    },
  ],
  showTitle: true,
  descriptions: {
    analysisAndProcessing: true,
    comments: true,
    introductoryText: false,
    nationalData: true,
  },
  dataExport: {
    included: true,
  },
  migration: {
    cycles: ['2020'],
  },
}
