// @ts-nocheck

const rankDataCols = [
  { idx: 0, type: 'text' },
  { idx: 1, type: 'text' },
  { idx: 2, type: 'decimal' },
  { idx: 3, type: 'decimal' },
  {
    idx: 4,
    type: 'select',
    options: [
      { optionName: 'ecologicalServices' },
      { optionName: 'waterProtection' },
      { optionName: 'soilProtection' },
      { optionName: 'healthProtection' },
      { optionName: 'infrastructureProtection' },
      { optionName: 'biosphericServices' },
      { optionName: 'biodiversityProtection' },
      { optionName: 'climateRegulation' },
      { optionName: 'socialServices' },
      { optionName: 'tourism' },
      { optionName: 'recreation' },
      { optionName: 'sportActivities' },
      { optionName: 'amenityServices' },
      { optionName: 'spiritualServices' },
      { optionName: 'culturalServices' },
      { optionName: 'historicalServices' },
      { optionName: 'otherServices' },
    ],
    optionsLabelKeyPrefix: 'panEuropean.2025.meta.select.forestServiceCategory',
  },
]

export const marketedServices2015 = {
  sectionName: 'marketedServices',
  sectionAnchor: '3.4',
  tableSections: [
    {
      tableSpecs: [
        {
          name: 'table_3_4',
          rows: [
            {
              idx: 'header_0',
              cols: [
                {
                  idx: 0,
                  colSpan: 1,
                  rowSpan: 2,
                  labelKey: 'panEuropean.marketedServices2015.rankValue',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 1,
                  colSpan: 1,
                  rowSpan: 2,
                  labelKey: 'panEuropean.marketedServices2015.nameOfServiceProduct',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 2,
                  colSpan: 1,
                  rowSpan: 2,
                  labelKey: 'panEuropean.marketedServices2015.unit',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 3,
                  colSpan: 2,
                  rowSpan: 1,
                  labelKey: 'panEuropean.marketedServices2015.serviceProvision',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 4,
                  colSpan: 1,
                  rowSpan: 2,
                  labelKey: 'panEuropean.marketedServices2015.forestServiceCategory',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
              ],
              type: 'header',
            },
            {
              idx: 'header_1',
              cols: [
                {
                  idx: 0,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.marketedServices2015.amountOfServiceProduct',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 1,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.marketedServices2015.value1000NationalCurrency',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
              ],
              type: 'header',
            },
            {
              idx: 0,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.marketedServices2015._01st',
                  className: 'fra-table__category-cell',
                },
                ...rankDataCols,
              ],
              variableExport: '_01st',
              labelKey: 'panEuropean.marketedServices2015._01st',
            },
            {
              idx: 1,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.marketedServices2015._02nd',
                  className: 'fra-table__category-cell',
                },
                ...rankDataCols,
              ],
              variableExport: '_02nd',
              labelKey: 'panEuropean.marketedServices2015._02nd',
            },
            {
              idx: 2,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.marketedServices2015._03rd',
                  className: 'fra-table__category-cell',
                },
                ...rankDataCols,
              ],
              variableExport: '_03rd',
              labelKey: 'panEuropean.marketedServices2015._03rd',
            },
            {
              idx: 3,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.marketedServices2015._04th',
                  className: 'fra-table__category-cell',
                },
                ...rankDataCols,
              ],
              variableExport: '_04th',
              labelKey: 'panEuropean.marketedServices2015._04th',
            },
            {
              idx: 4,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.marketedServices2015._05th',
                  className: 'fra-table__category-cell',
                },
                ...rankDataCols,
              ],
              variableExport: '_05th',
              labelKey: 'panEuropean.marketedServices2015._05th',
            },
            {
              idx: 5,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.marketedServices2015._06th',
                  className: 'fra-table__category-cell',
                },
                ...rankDataCols,
              ],
              variableExport: '_06th',
              labelKey: 'panEuropean.marketedServices2015._06th',
            },
            {
              idx: 6,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.marketedServices2015._07th',
                  className: 'fra-table__category-cell',
                },
                ...rankDataCols,
              ],
              variableExport: '_07th',
              labelKey: 'panEuropean.marketedServices2015._07th',
            },
            {
              idx: 7,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.marketedServices2015._08th',
                  className: 'fra-table__category-cell',
                },
                ...rankDataCols,
              ],
              variableExport: '_08th',
              labelKey: 'panEuropean.marketedServices2015._08th',
            },
            {
              idx: 8,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.marketedServices2015._09th',
                  className: 'fra-table__category-cell',
                },
                ...rankDataCols,
              ],
              variableExport: '_09th',
              labelKey: 'panEuropean.marketedServices2015._09th',
            },
            {
              idx: 9,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 1,
                  labelKey: 'panEuropean.marketedServices2015._10th',
                  className: 'fra-table__category-cell',
                },
                ...rankDataCols,
              ],
              variableExport: '_10th',
              labelKey: 'panEuropean.marketedServices2015._10th',
            },
            {
              idx: 10,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 4,
                  labelKey: 'panEuropean.marketedServices2015.remaining_total',
                  className: 'fra-table__category-cell',
                },
                { idx: 3, type: 'decimal' },
                { idx: 1, type: 'placeholder' },
              ],
              variableExport: 'remaining_total',
              labelKey: 'panEuropean.marketedServices2015.remaining_total',
              colSpan: 4,
            },
            {
              idx: 11,
              type: 'data',
              cols: [
                {
                  idx: 'header_0',
                  type: 'header',
                  colSpan: 4,
                  labelKey: 'panEuropean.marketedServices2015.total',
                  className: 'fra-table__category-cell',
                },
                {
                  idx: 3,
                  type: 'decimal',
                  migration: {
                    validateFns: {
                      '2025': [
                        `validatorEqualToSum(table_3_4.total['name_of_service_product'],
                  [table_3_4._10th['service_provision_value_1000_national_currency'],table_3_4._09th['service_provision_value_1000_national_currency'],
                  table_3_4._08th['service_provision_value_1000_national_currency'],table_3_4._07th['service_provision_value_1000_national_currency'],
                  table_3_4._06th['service_provision_value_1000_national_currency'],table_3_4._05th['service_provision_value_1000_national_currency'],
                  table_3_4._04th['service_provision_value_1000_national_currency'],table_3_4._03rd['service_provision_value_1000_national_currency'],
                  table_3_4._02nd['service_provision_value_1000_national_currency'],table_3_4._01st['service_provision_value_1000_national_currency']])`,
                      ],
                    },
                  },
                },
                { idx: 4, type: 'placeholder' },
              ],
              variableExport: 'total',
              labelKey: 'panEuropean.marketedServices2015.total',
              colSpan: 4,
            },
          ],
          tableDataRequired: [],
          print: { colBreakPoints: [], pageBreakAfter: false },
          dataExport: true,
          columnsExportAlways: [],
          columnsExport: [
            'name_of_service_product',
            'unit',
            'service_provision_amount_of_service_product',
            'service_provision_value_1000_national_currency',
            'forest_service_category',
          ],
        },
      ],
    },
    {
      titleKey: 'panEuropean.countryComments.countryComments',
      tableSpecs: [
        {
          name: 'country_comments_3_4_1',
          rows: [
            {
              idx: 'header_0',
              variableName: 'referenceAreaIfDifferentFromTotalFowlEGOwnershipClassOr1000Ha',
              cols: [
                {
                  idx: 0,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.countryComments.referenceAreaIfDifferentFromTotalFowlEGOwnershipClassOr1000Ha',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'textarea', colName: 'comment' },
              ],
              type: 'data',
            },
          ],
          tableDataRequired: [],
          print: { colBreakPoints: [], pageBreakAfter: false },
          dataExport: true,
          columnsExportAlways: [],
          columnsExport: [],
          migration: {
            cycles: ['2025'],
            columnNames: { '2025': ['comment'] },
          },
        },
      ],
    },
    {
      tableSpecs: [
        {
          name: 'country_comments_3_4_2',
          rows: [
            {
              idx: 'header_0',
              cols: [
                {
                  idx: 0,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.countryComments.category',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 1,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.countryComments.commentsRelatedToDataDefinitions',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                {
                  idx: 2,
                  colSpan: 1,
                  rowSpan: 1,
                  labelKey: 'panEuropean.countryComments.commentsOnTrend',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
              ],
              type: 'header',
            },
            {
              idx: 0,
              type: 'data',
              variableName: 'generalComments',
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  labelKey: 'panEuropean.countryComments.generalComments',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'textarea', colName: 'comment' },
                { idx: 1, type: 'textarea', colName: 'comment_trends' },
              ],
            },
            {
              idx: 1,
              type: 'data',
              variableName: 'first',
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  labelKey: 'panEuropean.countryComments.first',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'textarea', colName: 'comment' },
                { idx: 1, type: 'textarea', colName: 'comment_trends' },
              ],
            },
            {
              idx: 2,
              type: 'data',
              variableName: 'second',
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  labelKey: 'panEuropean.countryComments.second',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'textarea', colName: 'comment' },
                { idx: 1, type: 'textarea', colName: 'comment_trends' },
              ],
            },
            {
              idx: 3,
              type: 'data',
              variableName: 'third',
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  labelKey: 'panEuropean.countryComments.third',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'textarea', colName: 'comment' },
                { idx: 1, type: 'textarea', colName: 'comment_trends' },
              ],
            },
            {
              idx: 4,
              type: 'data',
              variableName: 'fourth',
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  labelKey: 'panEuropean.countryComments.fourth',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'textarea', colName: 'comment' },
                { idx: 1, type: 'textarea', colName: 'comment_trends' },
              ],
            },
            {
              idx: 5,
              type: 'data',
              variableName: 'fifth',
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  labelKey: 'panEuropean.countryComments.fifth',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'textarea', colName: 'comment' },
                { idx: 1, type: 'textarea', colName: 'comment_trends' },
              ],
            },
            {
              idx: 6,
              type: 'data',
              variableName: 'sixth',
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  labelKey: 'panEuropean.countryComments.sixth',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'textarea', colName: 'comment' },
                { idx: 1, type: 'textarea', colName: 'comment_trends' },
              ],
            },
            {
              idx: 7,
              type: 'data',
              variableName: 'seventh',
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  labelKey: 'panEuropean.countryComments.seventh',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'textarea', colName: 'comment' },
                { idx: 1, type: 'textarea', colName: 'comment_trends' },
              ],
            },
            {
              idx: 8,
              type: 'data',
              variableName: 'eighth',
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  labelKey: 'panEuropean.countryComments.eighth',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'textarea', colName: 'comment' },
                { idx: 1, type: 'textarea', colName: 'comment_trends' },
              ],
            },
            {
              idx: 9,
              type: 'data',
              variableName: 'ninth',
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  labelKey: 'panEuropean.countryComments.ninth',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'textarea', colName: 'comment' },
                { idx: 1, type: 'textarea', colName: 'comment_trends' },
              ],
            },
            {
              idx: 10,
              type: 'data',
              variableName: 'tenth',
              cols: [
                {
                  idx: 'header_0',
                  colSpan: 1,
                  labelKey: 'panEuropean.countryComments.tenth',
                  className: 'fra-table__header-cell',
                  type: 'header',
                },
                { idx: 0, type: 'textarea', colName: 'comment' },
                { idx: 1, type: 'textarea', colName: 'comment_trends' },
              ],
            },
          ],
          tableDataRequired: [],
          print: { colBreakPoints: [], pageBreakAfter: false },
          dataExport: true,
          columnsExportAlways: [],
          columnsExport: [],
          migration: {
            cycles: ['2025'],
            columnNames: { '2025': ['comment', 'comment_trends'] },
          },
        },
      ],
    },
  ],
  showTitle: true,
  descriptions: {
    analysisAndProcessing: true,
    comments: true,
    introductoryText: false,
    nationalData: true,
  },
  dataExport: {
    included: true,
  },
}
