export enum TrackId {
  footerCcLicense = 'footer-cc-license',
  footerContactUs = 'footer-contact-us',
  footerFaoTerms = 'footer-fao-terms',
  footerLicenses = 'footer-licenses',
  footerReportMisconduct = 'footer-report-misconduct',
  footerScamAlert = 'footer-scam-alert',
  footerSendFeedback = 'footer-send-feedback',
  footerTermsAndConditions = 'footer-terms-and-conditions',
  footerUserGuide = 'footer-user-guide',
  headerHome = 'header-home',
  headerLogin = 'header-login',
  landingDownloadPdf = 'landing-download-pdf',
  landingExploreKeyFindings = 'landing-explore-key-findings',
  landingPartnerEu = 'landing-partner-eu',
  landingPartnerFinland = 'landing-partner-finland',
  landingPartnerGef = 'landing-partner-gef',
  landingPartnerNorway = 'landing-partner-norway',
  landingReadMoreFraProcess = 'landing-read-more-fra-process',
  landingReadOnline = 'landing-read-online',
  landingSelectCountries = 'landing-select-countries',
  landingSelectGlobal = 'landing-select-global',
  landingSelectRegions = 'landing-select-regions',
}
