openapi: 3.0.0
paths:
  /cycle-data/table/table-data:
    get:
      summary: Get table data
      parameters:
        - $ref: '#/components/parameters/assessmentName'
        - $ref: '#/components/parameters/countryIso'
        - $ref: '#/components/parameters/cycleName'
        - in: query
          name: columns[]
          description: Array of columns to retrieve. For example, ["1990"].
          required: false
          schema:
            type: array
            items:
              type: string
            example: ["1990"]
          style: form
          explode: true
        - in: query
          name: countryISOs[]
          description: Array of country ISO codes. For example, ["FIN", "ITA"].
          required: true
          schema:
            type: array
            items:
              type: string
            example: ["FIN", "ITA"]
          style: form
          explode: true
        - in: query
          name: mergeOdp
          description: A flag indicating whether to merge ODP data. Defaults to "true" if omitted.
          required: false
          schema:
            type: string
            enum:
              - "true"
              - "false"
            default: "true"
            example: "true"
        - $ref: '#/components/parameters/fra2025tableNames'
        - in: query
          name: variables[]
          description: Array of variable names to retrieve. For example, ["forestArea"].
          required: false
          schema:
            type: array
            items:
              type: string
            example: ["forestArea"]
          style: form
          explode: true
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                description: The resulting table data.
                $ref: '#/components/schemas/RecordAssessmentData'
              example:
                fra:
                  "2020":
                    FIN:
                      extentOfForest:
                        "1990":
                          total:
                            odp: true
                            raw: "21875.33"
                            odpId: 231
                          otherLand:
                            odp: true
                            raw: "7589.76999"
                            odpId: 231
                          forestArea:
                            odp: true
                            raw: "21875.33"
                            odpId: 231
        '401':
          description: Unauthorized access.
