openapi: 3.0.0
paths:
  /cycle-data/table/table-data:
    get:
      tags:
        - Cycle data
      summary: Get table data
      parameters:
        - $ref: '#/components/parameters/assessmentName'
        - $ref: '#/components/parameters/countryIso'
        - $ref: '#/components/parameters/cycleName'
        - $ref: '#/components/parameters/columns'
        - $ref: '#/components/parameters/countryISOs'
        - in: query
          name: mergeOdp
          description: A flag indicating whether to merge ODP data. Defaults to "true" if omitted.
          required: false
          schema:
            type: string
            enum:
              - "true"
              - "false"
            default: "true"
            example: "true"
        - $ref: '#/components/parameters/fra2025tableNames'
        - $ref: '#/components/parameters/variables'
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                description: The resulting table data.
                $ref: '#/components/schemas/RecordAssessmentData'
              example:
                fra:
                  "2025":
                    FIN:
                      extentOfForest:
                        "1990":
                          total:
                            odp: true
                            raw: "21875.33"
                            odpId: 231
                          otherLand:
                            odp: true
                            raw: "7589.76999"
                            odpId: 231
                          forestArea:
                            odp: true
                            raw: "21875.33"
                            odpId: 231
        '401':
          description: Unauthorized access.
