name: Deploy to production

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0' # fetch all tags, default 1

      - name: Use Node.js 14.18.1
        uses: actions/setup-node@v1
        with:
          node-version: '14.18.1'
          always-auth: true
          auth-token: ${{secrets.ACCESS_TOKEN}}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@openforis'

      - run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - run: yarn test

      - name: Get the version
        id: app_version
        run: echo ::set-output name=APP_VERSION::$(git describe --always --tags)

      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_PRODUCTION}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          HD_APP_VERSION: ${{ steps.app_version.outputs.APP_VERSION }}
