name: Manual Database Backup

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to backup (production/development)'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - development
  push:
    branches:
      - 4113-github-action-db-backup
    paths:
      - '.github/workflows/heroku-db-backup.yml'

jobs:
  backup:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Create Heroku Postgres Backup
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ github.event.inputs.environment == 'production' && secrets.HEROKU_APP_NAME_PRODUCTION || secrets.HEROKU_APP_NAME_DEVELOPMENT }}
        run: |
          curl -n -X POST https://api.heroku.com/apps/$APP_NAME/pg-backups \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.heroku+json; version=3" \
            -H "Authorization: Bearer $HEROKU_API_KEY" 