name: Node.js CI

on:
  push:
    branches: [ feature/github-actions ]
  pull_request:
    branches: [ feature/github-actions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.15.0
      uses: actions/setup-node@v1
      with:
        node-version: '14.15.0'
    - name: Run tests with yarn
    - run: yarn test
      
