name: Run Unit and Integration Tests

on:
  pull_request:
    branches-ignore:
      - 'master'
      - 'production'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      run_tests: true

  tests:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Run unit and integration tests
        run: docker compose -f src/test/e2e/docker-compose.test.yml exec -T web yarn test
        env:
          NPM_GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Stop containers
        if: always()
        run: docker compose -f src/test/e2e/docker-compose.test.yml down -v
