name: Run Tests

on:
  push:
    branches-ignore:
      - 'master'
      - 'production'

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Download test database
        run: |
          mkdir -p ./db
          curl -L "${{ secrets.TEST_DATABASE_URL }}" -o ./db/backup

      - name: Build and start containers
        run: docker compose -f src/test/e2e/docker-compose.test.yml up -d
        env:
          NPM_GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # - name: Setup tmate session
      #   if: failure()
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true
      #     timeout-minutes: 30

      - name: Wait for services to be ready
        run: |
          timeout 300 bash -c 'until docker compose -f src/test/e2e/docker-compose.test.yml ps web | grep -q "healthy"; do sleep 5; done'

      - name: Run unit and integration tests
        run: docker compose -f src/test/e2e/docker-compose.test.yml exec -T web yarn test
        env:
          NPM_GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Create test results directory
        run: mkdir -p playwright-report

      - name: Run E2E tests
        if: always()
        run: |
          docker compose -f src/test/e2e/docker-compose.test.yml run \
            playwright npm run test:e2e
        env:
          NPM_GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Zip test results
        if: always()
        run: |
          cd src/test/e2e
          zip -r ../../../playwright-results.zip test-results/

      - name: Upload test results
        if: always() && !env.ACT
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: playwright-results.zip
          retention-days: 30

      - name: Setup tmate session
        if: failure()
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
          timeout-minutes: 30

      - name: Stop containers
        if: always()
        run: docker compose -f src/test/e2e/docker-compose.test.yml down -v

      - name: Cleanup database backup
        if: always()
        run: |
          rm -rf ./db
