name: Upload and translate sources

on:
  workflow_dispatch:
  push:
    paths: ["src/i18n/resources/en/**/*.json", "!src/i18n/resources/en/panEuropean/**"]
    branches: [development]

permissions:
  contents: write
  pull-requests: write

jobs:
  crowdin-upload-sources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin push
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      # Translation Memory: Translate untranslated keys with Translation Memory (TM)
      # (uses already approved keys)
      - name: Pre-translate from Translation Memory
        run: >
          npx --yes @crowdin/cli@4 pre-translate
          --method tm
          --translate-untranslated-only
          --auto-approve-option all
          --no-progress
          --no-colors
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      # Machine Translation: use Machine Translation for keys missed by TM
      - name: Pre-translate with Machine Translation
        run: >
          npx --yes @crowdin/cli@4 pre-translate
          --method mt
          --engine-id ${{ vars.CROWDIN_MT_ENGINE_ID }}
          --translate-untranslated-only
          --no-progress
          --no-colors
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

  crowdin-download:
    needs: crowdin-upload-sources
    uses: ./.github/workflows/translations-download-workflow.yml
    secrets: inherit
